USE quiz_db;
GO
--BÀI 10: TỪ VỰNG PHẦN 1
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「音 (おと)」 nghĩa là gì?', N'Giọng nói', N'Âm thanh, tiếng động', N'Bên phải', N'Thuốc', 'B'),
(N'「声 (こえ)」 nghĩa là gì?', N'Cầu', N'Giọng nói', N'Bên trái', N'Đèn giao thông', 'B'),
(N'「薬 (くすり)」 nghĩa là gì?', N'Âm thanh', N'Góc đường', N'Thuốc (uống, bôi,...)', N'Con đường', 'C'),
(N'「右 (みぎ)」 nghĩa là gì?', N'Cầu', N'Bên trái', N'Ngã 4', N'Bên phải', 'D'),
(N'「左 (ひだり)」 nghĩa là gì?', N'Âm thanh', N'Bên trái', N'Đèn giao thông', N'Thuốc', 'B'),
(N'「かど」 nghĩa là gì?', N'Con đường', N'Ngã 4', N'Bên phải', N'Góc đường, ngã 3', 'D'),
(N'「こうさてん」 nghĩa là gì?', N'Giọng nói', N'Cầu', N'Ngã 4, bùng binh', N'Góc đường', 'C'),
(N'「しんごう」 nghĩa là gì?', N'Cầu', N'Âm thanh', N'Đèn giao thông', N'Bên trái', 'C'),
(N'「はし」 nghĩa là gì?', N'Giọng nói', N'Ngã 4', N'Con đường', N'Cầu', 'D'),
(N'「みち」 nghĩa là gì?', N'Cầu', N'Âm thanh', N'Góc đường', N'Con đường', 'D'),
(N'「～つ目 (～つめ)」 nghĩa là gì?', N'Qua, băng qua', N'Thứ ~ (đếm thứ tự)', N'Một chút', N'Thẳng', 'B'),
(N'「さがします」 nghĩa là gì?', N'Rẽ, quẹo', N'Nghe thấy', N'Tìm kiếm', N'Uống thuốc', 'C'),
(N'「薬をのみます」 nghĩa là gì?', N'Băng qua', N'Nhìn thấy', N'Uống thuốc', N'Thẳng', 'C'),
(N'「まがります」 nghĩa là gì?', N'Tìm kiếm', N'Nghe thấy', N'Nhìn thấy', N'Rẽ, quẹo', 'D'),
(N'「わたります」 nghĩa là gì?', N'Rẽ, quẹo', N'Uống thuốc', N'Qua, băng qua', N'Nghe thấy', 'C'),
(N'「きこえます」 nghĩa là gì?', N'Băng qua', N'Nghe thấy', N'Đi thẳng', N'Nhìn thấy', 'B'),
(N'「みえます」 nghĩa là gì?', N'Rẽ', N'Tìm kiếm', N'Nhìn thấy', N'Nghe thấy', 'C'),
(N'「まっすぐ」 nghĩa là gì?', N'Bên phải', N'Góc đường', N'Thẳng (phía trước)', N'Bên trái', 'C'),
(N'「よくわかりません」 nghĩa là gì?', N'Nghe thấy', N'Hầu như không hiểu', N'Nhìn thấy', N'Hiểu rất rõ', 'B'),
(N'「ちょっと」 nghĩa là gì?', N'Bên trái', N'Một chút, tương đối', N'Ngã 4', N'Rất nhiều', 'B'),
(N'「ええと」 nghĩa là gì?', N'Cầu', N'Ờ, à (ngập ngừng)', N'Thẳng', N'Nghe thấy', 'B');

--BÀI 10: TỪ VỰNG PHẦN 2
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「カーテン」 nghĩa là gì?', N'Hành lý', N'Quà lưu niệm', N'Rèm, màn cửa', N'Rác', 'C'),
(N'「おきゃくさん」 nghĩa là gì?', N'Rèm cửa', N'Khách hàng', N'Rác', N'Mọi người', 'B'),
(N'「ごみ」 nghĩa là gì?', N'Hành lý', N'Quà lưu niệm', N'Sách quảng cáo', N'Rác', 'D'),
(N'「手 (て)」 nghĩa là gì?', N'Mắt', N'Cửa', N'Tay', N'Chân', 'C'),
(N'「にもつ」 nghĩa là gì?', N'Rác', N'Hành lý, bưu phẩm', N'Quà lưu niệm', N'Rèm cửa', 'B'),
(N'「パンフレット」 nghĩa là gì?', N'Rác', N'Hành lý', N'Tay', N'Sách quảng cáo, giới thiệu', 'D'),
(N'「ほか」 nghĩa là gì?', N'Nguy hiểm', N'Ngoài ra, khác', N'Quan trọng', N'Chậm trễ', 'B'),
(N'「みなさん」 nghĩa là gì?', N'Rác', N'Khách hàng', N'Mọi người', N'Hành lý', 'C'),
(N'「おみやげ」 nghĩa là gì?', N'Rác', N'Rèm cửa', N'Quà lưu niệm', N'Khách hàng', 'C'),
(N'「おします」 nghĩa là gì?', N'Ngồi', N'Vứt bỏ', N'Ấn, bấm', N'Đứng', 'C'),
(N'「すわります」 nghĩa là gì?', N'Vào', N'Băng qua', N'Ngồi', N'Đứng', 'C'),
(N'「たちます」 nghĩa là gì?', N'Chậm trễ', N'Đứng', N'Ngồi', N'Vứt bỏ', 'B'),
(N'「はいります」 nghĩa là gì?', N'Ngồi', N'Mất', N'Đứng', N'Vào', 'D'),
(N'「なくします」 nghĩa là gì?', N'Vứt bỏ', N'Chậm trễ', N'Mất', N'Đem về', 'C'),
(N'「もってかえります」 nghĩa là gì?', N'Chậm trễ', N'Vứt bỏ', N'Đem về', N'Mất', 'C'),
(N'「おくれます」 nghĩa là gì?', N'Ngồi', N'Chậm trễ', N'Đứng', N'Vào', 'B'),
(N'「すてます」 nghĩa là gì?', N'Chậm trễ', N'Vứt bỏ, ném', N'Đem về', N'Tập trung', 'B'),
(N'「しゅうごうします」 nghĩa là gì?', N'Chậm trễ', N'Tập hợp, tập trung', N'Ngồi', N'Đứng', 'B'),
(N'「あぶない」 nghĩa là gì?', N'Khác', N'Quan trọng', N'Nguy hiểm', N'Phiền phức', 'C'),
(N'「たいせつ（な）」 nghĩa là gì?', N'Quan trọng', N'Nguy hiểm', N'Phiền phức', N'Rác', 'A'),
(N'「めいわく（な）」 nghĩa là gì?', N'Nguy hiểm', N'Làm phiền, phiền phức', N'Quan trọng', N'Khác', 'B');

--BÀI 10: TỪ VỰNG PHẦN 3
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「クマ」 nghĩa là gì?', N'Con chim', N'Con gấu', N'Con khỉ', N'Con voi', 'B'),
(N'「コアラ」 nghĩa là gì?', N'Con khỉ', N'Gấu trúc', N'Gấu Koala', N'Chim cánh cụt', 'C'),
(N'「サル」 nghĩa là gì?', N'Con khỉ', N'Con voi', N'Con chim', N'Gấu Koala', 'A'),
(N'「ゾウ」 nghĩa là gì?', N'Chim cánh cụt', N'Con chim', N'Con voi', N'Con gấu', 'C'),
(N'「とり」 nghĩa là gì?', N'Con voi', N'Con chim', N'Gấu trúc', N'Con khỉ', 'B'),
(N'「パンダ」 nghĩa là gì?', N'Con gấu', N'Con chim', N'Gấu trúc', N'Chim cánh cụt', 'C'),
(N'「ペンギン」 nghĩa là gì?', N'Con chim', N'Con voi', N'Chim cánh cụt', N'Con khỉ', 'C'),
(N'「入口 (いりぐち)」 nghĩa là gì?', N'Lối vào, cửa vào', N'Vòng đu quay', N'Quả bóng', N'Lối ra', 'A'),
(N'「出口 (でぐち)」 nghĩa là gì?', N'Lối vào', N'Lối ra, cửa ra', N'Con đường', N'Quả bóng', 'B'),
(N'「えさ」 nghĩa là gì?', N'Trái chuối', N'Cái bụng', N'Quả bóng', N'Thức ăn cho động vật', 'D'),
(N'「おなか」 nghĩa là gì?', N'Thức ăn', N'Quả bóng', N'Cái bụng', N'Con chim', 'C'),
(N'「かんらんしゃ」 nghĩa là gì?', N'Trái chuối', N'Vòng đu quay', N'Lối ra', N'Quả bóng', 'B'),
(N'「バナナ」 nghĩa là gì?', N'Con khỉ', N'Quả bóng', N'Cái bụng', N'Trái chuối', 'D'),
(N'「ボール」 nghĩa là gì?', N'Con chim', N'Con voi', N'Quả bóng', N'Trái chuối', 'C'),
(N'「～たち」 nghĩa là gì?', N'Bạn bè', N'Con vật', N'Người (số nhiều)', N'Đồ vật', 'C'),
(N'「あるきます」 nghĩa là gì?', N'Chạy', N'Ăn', N'Đi bộ', N'Bay', 'C'),
(N'「とびます」 nghĩa là gì?', N'Ngủ', N'Bay', N'Đi bộ', N'Chạy', 'B'),
(N'「なります」 nghĩa là gì?', N'Bay', N'Ăn', N'Trở nên', N'Đi bộ', 'C'),
(N'「あそこのベンチで休みましょう。」 nghĩa là gì?', N'Hãy ăn ở ghế kia', N'Hãy nghỉ ngơi ở ghế đằng kia nào', N'Hãy chạy đến ghế kia', N'Hãy đi đến ghế kia', 'B'),
(N'「休みます」 nghĩa là gì?', N'Bay', N'Ăn', N'Nghỉ ngơi, vắng mặt', N'Chạy', 'C'),
(N'「やります」 nghĩa là gì?', N'Ngủ', N'Làm, hành động', N'Bay', N'Đi bộ', 'B'),
(N'「おなかがすきます」 nghĩa là gì?', N'Khát nước', N'Đói bụng', N'Đau', N'Mệt mỏi', 'B'),
(N'「のどがかわきます」 nghĩa là gì?', N'Khát nước', N'Đau', N'Mệt mỏi', N'Đói bụng', 'A'),
(N'「つかれます」 nghĩa là gì?', N'Đau', N'Khát nước', N'Đói bụng', N'Mệt mỏi', 'D'),
(N'「いたい」 nghĩa là gì?', N'Mệt mỏi', N'Đau', N'Khát nước', N'Đói bụng', 'B'),
(N'「そろそろ」 nghĩa là gì?', N'Đột nhiên', N'Ngay lập tức', N'Dần dần', N'Nhanh chóng', 'C'),
(N'「ほんとうだ」 nghĩa là gì?', N'Không chắc', N'Hẳn vậy', N'Không đúng', N'Có lẽ', 'B'),
(N'「とくに」 nghĩa là gì?', N'Ít khi', N'Nhất là, đặc biệt là', N'Thỉnh thoảng', N'Không bao giờ', 'B');

--BÀI 10: KANJI
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「駅 (えき)」 nghĩa là gì?', N'Con đường', N'Nhà ga', N'Rạp chiếu phim', N'Bản đồ', 'B'),
(N'「駅長 (えきちょう)」 nghĩa là gì?', N'Khách hàng', N'Nhân viên bán vé', N'Trưởng nhà ga', N'Người lái tàu', 'C'),
(N'「上 (うえ)」 nghĩa là gì?', N'Dưới', N'Trên', N'Bên trái', N'Con đường', 'B'),
(N'「上京 (じょうきょう)」 nghĩa là gì?', N'Đi bộ', N'Tới Tokyo', N'Đi tàu', N'Đi xuống xe', 'B'),
(N'「下 (した)」 nghĩa là gì?', N'Ngầm', N'Dưới', N'Trên', N'Bên phải', 'B'),
(N'「下車 (げしゃ)」 nghĩa là gì?', N'Xuống xe', N'Chạy xe', N'Lên xe', N'Đi bộ', 'A'),
(N'「上下 (じょうげ)」 nghĩa là gì?', N'Trong ngoài', N'Lên xuống xe', N'Trên dưới', N'Bên trái bên phải', 'C'),
(N'「土地 (とち)」 nghĩa là gì?', N'Tòa nhà', N'Đất đai', N'Con đường', N'Nhà ga', 'B'),
(N'「地下 (ちか)」 nghĩa là gì?', N'Đường quốc lộ', N'Trên mặt đất', N'Ngầm', N'Bên trên', 'C'),
(N'「地図 (ちず)」 nghĩa là gì?', N'Con đường', N'Bản đồ', N'Thư viện', N'Hình vẽ', 'B'),
(N'「図 (ず)」 nghĩa là gì?', N'Bản đồ', N'Hình vẽ', N'Nhà ga', N'Đất đai', 'B'),
(N'「図書館 (としょかん)」 nghĩa là gì?', N'Rạp chiếu phim', N'Nhà trọ', N'Bộ sưu tập', N'Thư viện', 'D'),
(N'「旅館 (りょかん)」 nghĩa là gì?', N'Nhà trọ', N'Rạp chiếu phim', N'Thư viện', N'Trung tâm hội nghị', 'A'),
(N'「会館 (かいかん)」 nghĩa là gì?', N'Bản đồ', N'Đường quốc lộ', N'Trung tâm', N'Nhà ga', 'C'),
(N'「映画館 (えいがかん)」 nghĩa là gì?', N'Nhà ga', N'Nhà trọ', N'Rạp chiếu phim', N'Thư viện', 'C'),
(N'「右 (みぎ)」 nghĩa là gì?', N'Phía sau', N'Bên phải', N'Phía trước', N'Bên trái', 'B'),
(N'「左 (ひだり)」 nghĩa là gì?', N'Bên phải', N'Phía trước', N'Bên trái', N'Phía sau', 'C'),
(N'「左右 (さゆう)」 nghĩa là gì?', N'Trong ngoài', N'Trước sau', N'Trái phải', N'Trên dưới', 'C'),
(N'「道 (みち)」 nghĩa là gì?', N'Nhà ga', N'Rạp chiếu phim', N'Con đường', N'Bản đồ', 'C'),
(N'「書道 (しょどう)」 nghĩa là gì?', N'Đường xe chạy', N'Bản đồ', N'Thư pháp', N'Nhà trọ', 'C'),
(N'「国道 (こくどう)」 nghĩa là gì?', N'Đường xe đạp', N'Đường quốc lộ', N'Đường làng', N'Đường ngầm', 'B'),
(N'「車道 (しゃどう)」 nghĩa là gì?', N'Đường sắt', N'Đường đi bộ', N'Đường xe chạy', N'Đường ngầm', 'C');

--BÀI 10: NGỮ PHÁP
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「もうレポートを＿＿＿か。」', N'しました', N'します', N'しません', N'していました', 'A'),
(N'「もう昼ごはんを食べましたか。」ー「いいえ、＿＿＿。」', N'まだ食べません', N'もう食べません', N'まだ食べていません', N'まだ食べました', 'C'),
(N'「もう宿題をしましたか。」ー「はい、＿＿＿。」', N'まだしました', N'もうしました', N'まだしません', N'もうしません', 'B'),
(N'「ちょっとコンビニへパンを＿＿＿きます。」', N'買います', N'買いに', N'買わない', N'買って', 'D'),
(N'「駅前で新聞を＿＿＿きます。」', N'買わないで', N'買いました', N'買って', N'買い', 'C'),
(N'「ジュースを買って＿＿＿。」', N'みます', N'きます', N'あります', N'います', 'B'),
(N'「山が＿＿＿。」', N'みえます', N'みない', N'みます', N'みています', 'A'),
(N'「音楽が＿＿＿。」', N'ききます', N'きこえます', N'きいています', N'きかない', 'B'),
(N'「あそこに富士山が＿＿＿。」', N'みない', N'みて', N'みえます', N'みます', 'C'),
(N'「ラジオの音が＿＿＿。」', N'きこえます', N'ききます', N'きかない', N'きいて', 'A'),
(N'「ここで写真を＿＿＿もいいですか。」', N'とります', N'とって', N'とった', N'とらない', 'B'),
(N'「ここでたばこを＿＿＿もいいですか。」', N'すわない', N'すって', N'すいます', N'すった', 'B'),
(N'「ここで休ん＿＿＿もいいですか。」', N'ない', N'で', N'て', N'だ', 'B'),
(N'「ここで写真を＿＿＿ください。」', N'とって', N'とらないで', N'とります', N'とった', 'B'),
(N'「ここでごみを＿＿＿ください。」', N'すてます', N'すてないで', N'すてました', N'すてて', 'B'),
(N'「ここでたばこを＿＿＿ください。」', N'すいます', N'すわないで', N'すって', N'すいました', 'B'),
(N'「コアラがえさを＿＿＿。」', N'食べました', N'食べます', N'食べています', N'食べない', 'C'),
(N'「子どもたちが公園で＿＿＿。」', N'遊びました', N'遊ばない', N'遊んでいます', N'遊びます', 'C'),
(N'「先生が教室に＿＿＿。」', N'入っています', N'入りました', N'入らない', N'入ります', 'A'),
(N'「寒く＿＿＿。」', N'あります', N'なります', N'いました', N'しました', 'B'),
(N'「元気＿＿＿。」', N'にします', N'になります', N'です', N'します', 'B'),
(N'「有名＿＿＿。」', N'です', N'あります', N'になります', N'します', 'C'),
(N'「医者＿＿＿なりたいです。」', N'を', N'で', N'に', N'が', 'C'),
(N'「先生＿＿＿なりたいです。」', N'に', N'が', N'で', N'を', 'A'),
(N'「エンジニア＿＿＿なりたいです。」', N'に', N'を', N'で', N'が', 'A'),
(N'「25歳＿＿＿なりました。」', N'で', N'が', N'に', N'を', 'C'),
(N'「きれい＿＿＿なりました。」', N'く', N'で', N'に', N'が', 'C'),
(N'「さむく＿＿＿。」', N'しました', N'なりました', N'ありました', N'いました', 'B'),
(N'「先生の声が＿＿＿。」', N'きいて', N'きこえます', N'ききます', N'きかない', 'B'),
(N'「遠くに山が＿＿＿。」', N'みえます', N'みて', N'みます', N'みない', 'A'),
(N'「もう映画を＿＿＿か。」', N'見ない', N'見ました', N'見て', N'見ます', 'B'),
(N'「いいえ、まだ＿＿＿。」', N'見ていません', N'見ました', N'見ない', N'見ます', 'A'),
(N'「ちょっとジュースを＿＿＿きます。」', N'買って', N'買いました', N'買い', N'買わない', 'A'),
(N'「友だちに電話を＿＿＿きます。」', N'かけない', N'かけました', N'かけて', N'かけます', 'C'),
(N'「ここで食べ＿＿＿もいいですか。」', N'ます', N'ない', N'て', N'た', 'C'),
(N'「ここで走ら＿＿＿ください。」', N'ないで', N'て', N'た', N'ます', 'A'),
(N'「犬がボールで＿＿＿。」', N'遊びました', N'遊びます', N'遊ばない', N'遊んでいます', 'D'),
(N'「子どもが泣い＿＿＿。」', N'ない', N'ています', N'ました', N'ます', 'B'),
(N'「だんだん暑く＿＿＿。」', N'ありました', N'なりました', N'しました', N'いました', 'B'),
(N'「元気＿＿＿なりました。」', N'く', N'に', N'で', N'が', 'B');