USE quiz_db;
GO
--BÀI 9: TỪ VỰNG PHẦN 1
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'Nghĩa của 「アクション」 là gì?', N'Nhạc Pop', N'Hành động', N'Truyện tranh', N'Bánh kẹo', 'B'),
(N'Nghĩa của 「おかし」 là gì?', N'Bể bơi', N'Tem', N'Bánh kẹo', N'Phim truyền hình', 'C'),
(N'Nghĩa của 「きって」 là gì?', N'Nhạc cổ điển', N'Tem', N'Câu cá', N'Tiểu thuyết', 'B'),
(N'Nghĩa của 「クラシック」 là gì?', N'Nhạc cổ điển', N'Bể bơi', N'Bánh kẹo', N'Truyện tranh', 'A'),
(N'Nghĩa của 「ポップス」 là gì?', N'Nhạc cổ điển', N'Phim truyền hình', N'Nhạc Pop', N'Câu cá', 'C'),
(N'Nghĩa của 「しょうせつ」 là gì?', N'Truyện tranh', N'Bơi', N'Tiểu thuyết', N'Tem', 'C'),
(N'Nghĩa của 「まんが」 là gì?', N'Tiểu thuyết', N'Truyện tranh', N'Nhạc Pop', N'Bể bơi', 'B'),
(N'Nghĩa của 「つり」 là gì?', N'Bơi', N'Câu cá', N'Bánh kẹo', N'Phim truyền hình', 'B'),
(N'Nghĩa của 「ドラマ」 là gì?', N'Câu cá', N'Phim truyền hình', N'Nhạc cổ điển', N'Tem', 'B'),
(N'Nghĩa của 「プール」 là gì?', N'Bể bơi', N'Truyện tranh', N'Nhạc Pop', N'Bơi', 'A'),
(N'Nghĩa của 「さいきん」 là gì?', N'Thường', N'Luôn luôn', N'Gần đây', N'Đặc biệt', 'C'),
(N'Nghĩa của 「～にち」 là gì?', N'~ ngày', N'~ tuần', N'~ tháng', N'~ năm', 'A'),
(N'Nghĩa của 「～しゅうかん」 là gì?', N'~ tháng', N'~ tuần', N'~ ngày', N'~ năm', 'B'),
(N'Nghĩa của 「～かげつ」 là gì?', N'~ tuần', N'~ tháng', N'~ năm', N'~ lần', 'B'),
(N'Nghĩa của 「～ねん」 là gì?', N'~ năm', N'~ tháng', N'~ lần', N'~ ngày', 'A'),
(N'Nghĩa của 「～かい」 là gì?', N'~ quyển', N'~ lần', N'~ ly', N'~ cái dài', 'B'),
(N'Nghĩa của 「～さつ」 là gì?', N'~ quyển', N'~ ly', N'~ lần', N'~ năm', 'A'),
(N'Nghĩa của 「～はい」 là gì?', N'~ ly, cốc', N'~ quyển', N'~ lần', N'~ năm', 'A'),
(N'Nghĩa của 「～ほん」 là gì?', N'~ cái, chiếc, cây (vật dài)', N'~ ly', N'~ quyển', N'~ lần', 'A'),
(N'Nghĩa của 「りょうり」 là gì?', N'Bơi', N'Bánh kẹo', N'Món ăn', N'Nhạc Pop', 'C'),
(N'Nghĩa của 「およぎます」 là gì?', N'Lái xe', N'Bơi', N'Vẽ', N'Thu thập', 'B'),
(N'Nghĩa của 「かきます」 là gì?', N'Vẽ, tả', N'Bơi', N'Lái xe', N'Thu thập', 'A'),
(N'Nghĩa của 「あつめます」 là gì?', N'Bơi', N'Thu thập, tập hợp', N'Lái xe', N'Vẽ', 'B'),
(N'Nghĩa của 「うんてんします」 là gì?', N'Lái xe', N'Bơi', N'Thu thập', N'Vẽ', 'A'),
(N'Nghĩa của 「とくに」 là gì?', N'Đặc biệt', N'Thỉnh thoảng', N'Thường', N'Luôn luôn', 'A'),
(N'Nghĩa của 「いつも」 là gì?', N'Thường', N'Luôn luôn', N'Thỉnh thoảng', N'Không lắm', 'B'),
(N'Nghĩa của 「よく」 là gì?', N'Thường', N'Thỉnh thoảng', N'Luôn luôn', N'Không lắm', 'A'),
(N'Nghĩa của 「ときどき」 là gì?', N'Thỉnh thoảng', N'Thường', N'Luôn luôn', N'Không lắm', 'A'),
(N'Nghĩa của 「あまり」 là gì?', N'Không ~ lắm', N'Hoàn toàn không', N'Luôn luôn', N'Thường', 'A'),
(N'Nghĩa của 「ぜんぜん」 là gì?', N'Hoàn toàn không', N'Không lắm', N'Thỉnh thoảng', N'Luôn luôn', 'A'),
(N'Nghĩa của 「でも」 là gì?', N'Và', N'Nhưng, tuy nhiên', N'Hoặc', N'Bởi vì', 'B'),
(N'Nghĩa của 「だけ」 là gì?', N'Chỉ', N'Nhiều', N'Thường', N'Đặc biệt', 'A');

--BÀI 9: TỪ VỰNG PHẦN 2
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'Nghĩa của 「イベント」 là gì?', N'Khiêu vũ', N'Sự kiện', N'Câu lạc bộ', N'Cuộc thi', 'B'),
(N'Nghĩa của 「コンテスト」 là gì?', N'Sự kiện', N'Lớp học', N'Cuộc thi', N'Thư pháp', 'C'),
(N'Nghĩa của 「書道（しょどう）」 là gì?', N'Câu lạc bộ', N'Sự lặn xuống', N'Thư pháp', N'Khiêu vũ', 'C'),
(N'Nghĩa của 「ダイビング」 là gì?', N'Học', N'Khiêu vũ', N'Sự kiện', N'Sự lặn xuống, lao xuống', 'D'),
(N'Nghĩa của 「ダンス」 là gì?', N'Lớp học', N'Khiêu vũ', N'Thư pháp', N'Cuộc thi', 'B'),
(N'Nghĩa của 「～クラブ」 là gì?', N'Lớp học ~', N'Câu lạc bộ ~', N'Sự kiện', N'Học', 'B'),
(N'Nghĩa của 「きょうしつ」 là gì?', N'Sự kiện', N'Cuộc thi', N'Lớp học ~', N'Câu lạc bộ', 'C'),
(N'Nghĩa của 「ならいます」 là gì?', N'Tham gia', N'Học', N'Đăng ký', N'Lên', 'B'),
(N'Nghĩa của 「のります」 là gì?', N'Tham gia', N'Gia nhập', N'Lên', N'Đăng ký', 'C'),
(N'Nghĩa của 「はいります」 là gì?', N'Đăng ký', N'Có thể', N'Vào, gia nhập, tham gia', N'Học', 'C'),
(N'Nghĩa của 「もうしこみます」 là gì?', N'Học', N'Tham gia', N'Lên', N'Đăng ký', 'D'),
(N'Nghĩa của 「できます」 là gì?', N'Học', N'Có thể', N'Tham gia', N'Đăng ký', 'B'),
(N'Nghĩa của 「さんかします」 là gì?', N'Học', N'Tham gia', N'Gia nhập', N'Có thể', 'B'),
(N'Nghĩa của 「すごい」 là gì?', N'Giỏi', N'Nhiều', N'Tuyệt vời', N'Tham gia', 'C'),
(N'Nghĩa của 「いるいる（な）」 là gì?', N'Lớp học', N'Nhiều, đa dạng', N'Giỏi', N'Tuyệt vời', 'B'),
(N'Nghĩa của 「じょうずに」 là gì?', N'Đăng ký', N'Thành thạo, giỏi', N'Nhiều', N'Sự kiện', 'B');

--BÀI 9: TỪ VỰNG PHẦN 3
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'Nghĩa của 「うけつけ」 là gì?', N'Số điện thoại', N'Quầy lễ tân, thường trực', N'Thẻ', N'Địa chỉ', 'B'),
(N'Nghĩa của 「カード」 là gì?', N'Bài tập về nhà', N'Địa chỉ', N'Thẻ', N'Số ~', 'C'),
(N'Nghĩa của 「外国人登録証」 là gì?', N'Số điện thoại', N'Chứng nhận đăng ký người nước ngoài', N'Quầy lễ tân', N'Thẻ', 'B'),
(N'Nghĩa của 「じゅうしょ」 là gì?', N'Số điện thoại', N'Địa chỉ', N'Bài tập về nhà', N'Thẻ', 'B'),
(N'Nghĩa của 「しゅくだい」 là gì?', N'Địa chỉ', N'Bài tập về nhà', N'Số ~', N'Thẻ', 'B'),
(N'Nghĩa của 「でんわばんごう」 là gì?', N'Bài tập', N'Số điện thoại', N'Quầy lễ tân', N'Thẻ', 'B'),
(N'Nghĩa của 「～ばん」 là gì?', N'Địa chỉ', N'Số điện thoại', N'Số ~', N'Thẻ', 'C'),
(N'Nghĩa của 「いいます」 là gì?', N'Trả tiền', N'Nói', N'Xuống (xe)', N'Cho xem', 'B'),
(N'Nghĩa của 「はらいます」 là gì?', N'Cho xem', N'Trả, chi trả', N'Xuống (tàu, xe)', N'Đặt trước', 'B'),
(N'Nghĩa của 「おります」 là gì?', N'Xuống (tàu, xe)', N'Nói', N'Cho xem', N'Trả tiền', 'A'),
(N'Nghĩa của 「みせます」 là gì?', N'Nói', N'Cho xem', N'Xuống xe', N'Đặt trước', 'B'),
(N'Nghĩa của 「よやくします」 là gì?', N'Trả tiền', N'Nói', N'Đặt trước', N'Số điện thoại', 'C'),
(N'Nghĩa của 「どうやって」 là gì?', N'Khi nào', N'Làm thế nào', N'Ở đâu', N'Tại sao', 'B');

--BÀI 9: KANJI
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'Nghĩa của 「好き（すき）」 là gì?', N'Vui vẻ', N'Thích', N'Âm thanh', N'Bài hát', 'B'),
(N'Nghĩa của 「大好き（だいすき）」 là gì?', N'Du lịch', N'Rất thích', N'Xe hơi', N'Âm nhạc', 'B'),
(N'Nghĩa của 「大好物（だいこうぶつ）」 là gì?', N'Bài hát', N'Món yêu thích', N'Nước biển', N'Ngoại ngữ', 'B'),
(N'Nghĩa của 「歌（うた）」 là gì?', N'Âm thanh', N'Xe hơi', N'Bài hát', N'Vui vẻ', 'C'),
(N'Nghĩa của 「歌う（うたう）」 là gì?', N'Hát', N'Kế hoạch', N'Du lịch', N'Âm nhạc', 'A'),
(N'Nghĩa của 「国歌（こっか）」 là gì?', N'Phim', N'Âm nhạc', N'Quốc ca', N'Bài hát', 'C'),
(N'Nghĩa của 「短歌（たんか）」 là gì?', N'Âm thanh', N'Quốc ca', N'Thơ ngắn', N'Phim', 'C'),
(N'Nghĩa của 「音（おと）」 là gì?', N'Xe hơi', N'Âm thanh', N'Kế hoạch', N'Bài hát', 'B'),
(N'Nghĩa của 「音読み（おんよみ）」 là gì?', N'Âm nhạc', N'Âm On', N'Bài hát', N'Du lịch', 'B'),
(N'Nghĩa của 「楽しい（たのしい）」 là gì?', N'Bài hát', N'Biển', N'Vui vẻ', N'Âm thanh', 'C'),
(N'Nghĩa của 「音楽（おんがく）」 là gì?', N'Âm nhạc', N'Du lịch', N'Xe hơi', N'Bài hát', 'A'),
(N'Nghĩa của 「車（くるま）」 là gì?', N'Biển', N'Phim', N'Xe hơi', N'Âm thanh', 'C'),
(N'Nghĩa của 「映画（えいが）」 là gì?', N'Bài hát', N'Phim', N'Âm nhạc', N'Du lịch', 'B'),
(N'Nghĩa của 「計画（けいかく）」 là gì?', N'Du lịch', N'Xe hơi', N'Kế hoạch, dự án', N'Bài hát', 'C'),
(N'Nghĩa của 「旅（たび）」 là gì?', N'Chuyến đi, du lịch', N'Biển', N'Âm thanh', N'Bài hát', 'A'),
(N'Nghĩa của 「旅行（りょこう）」 là gì?', N'Âm nhạc', N'Du lịch', N'Xe hơi', N'Bài hát', 'B'),
(N'Nghĩa của 「海（うみ）」 là gì?', N'Âm thanh', N'Biển', N'Nước biển', N'Bài hát', 'B'),
(N'Nghĩa của 「海水（かいすい）」 là gì?', N'Biển', N'Xe hơi', N'Nước biển', N'Âm nhạc', 'C'),
(N'Nghĩa của 「外国（がいこく）」 là gì?', N'Ngoại ngữ', N'Nước ngoài', N'Người nước ngoài', N'Biển', 'B'),
(N'Nghĩa của 「外国語（がいこくご）」 là gì?', N'Nước ngoài', N'Ngoại ngữ', N'Xe hơi', N'Người nước ngoài', 'B'),
(N'Nghĩa của 「外国人（がいこくじん）」 là gì?', N'Ngoại ngữ', N'Nước ngoài', N'Bài hát', N'Người nước ngoài', 'D'),
(N'Nghĩa của 「海外（かいがい）」 là gì?', N'Hải ngoại, nước ngoài', N'Âm nhạc', N'Du lịch', N'Biển', 'A'),
(N'Nghĩa của 「社外（しゃがい）」 là gì?', N'Ngoại ngữ', N'Ngoài công ty', N'Biển', N'Nước ngoài', 'B'),
(N'Nghĩa của 「外（そと）」 trong 「家の外」 là gì?', N'Bên trong', N'Du lịch', N'Bên ngoài', N'Biển', 'C');

--BÀI 9: NGỮ PHÁP
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「いきます」の辞書形は何ですか？', N'いきる', N'いく', N'いった', N'いけば', 'B'),
(N'「みます」の辞書形は何ですか？', N'みた', N'みる', N'みよう', N'みて', 'B'),
(N'「べんきょうします」 thuộc nhóm động từ nào?', N'Nhóm 1', N'Nhóm 3', N'Nhóm 2', N'Nhóm đặc biệt', 'B'),
(N'Động từ nhóm 1 chuyển sang thể từ điển như thế nào?', N'ます → う', N'ます → る', N'ます → た', N'ます → て', 'A'),
(N'「しゅみはN/Vることです」 nghĩa là gì?', N'Tôi có thể ...', N'Sở thích là ...', N'Tôi muốn ...', N'Tôi đang ...', 'B'),
(N'わたしのしゅみはおんがくを（　　　）ことです。', N'ききます', N'きく', N'きいて', N'きいた', 'B'),
(N'彼の趣味は映画を（　　　）ことです。', N'みます', N'みる', N'みた', N'みて', 'B'),
(N'一週間に一回映画を（　　　）。', N'みる', N'みます', N'みました', N'みたい', 'B'),
(N'「いつも」 nghĩa là gì?', N'Luôn luôn', N'Không lắm', N'Hoàn toàn không', N'Thỉnh thoảng', 'A'),
(N'「よく」 nghĩa là gì?', N'Luôn luôn', N'Thường', N'Không lắm', N'Hoàn toàn không', 'B'),
(N'「ときどき」 nghĩa là gì?', N'Thường', N'Luôn luôn', N'Thỉnh thoảng', N'Không bao giờ', 'C'),
(N'「あまり」 thường đi với dạng nào?', N'Khẳng định', N'Phủ định', N'Câu hỏi', N'Mệnh lệnh', 'B'),
(N'「ぜんぜん」 thường đi với dạng nào?', N'Khẳng định', N'Câu hỏi', N'Phủ định', N'Mệnh lệnh', 'C'),
(N'私はあまりテレビを（　　　）。', N'みます', N'みません', N'みました', N'みたい', 'B'),
(N'彼はぜんぜんお酒を（　　　）。', N'のみます', N'のみたい', N'のみません', N'のみました', 'C'),
(N'Nができます nghĩa là gì?', N'Có thể làm N', N'Muốn N', N'Đã làm N', N'Không thể N', 'A'),
(N'私は日本語が（　　　）。', N'します', N'できます', N'あります', N'います', 'B'),
(N'私は漢字を読むことが（　　　）。', N'あります', N'できます', N'います', N'します', 'B'),
(N'「なかなか〜できません」 nghĩa là gì?', N'Rất dễ', N'Luôn luôn làm', N'Khó mà làm được', N'Thường làm', 'C'),
(N'彼はなかなか日本語を話すことが（　　　）。', N'できます', N'できません', N'しました', N'します', 'B'),
(N'V1て、V2て…Vます dùng để làm gì?', N'Giải thích lý do', N'Hỏi đường', N'Liệt kê hành động', N'Đưa ra mệnh lệnh', 'C'),
(N'ジョギングをして、シャワーをあびて、（　　　）。', N'いく', N'いきます', N'いった', N'いきたい', 'B'),
(N'Vて、それからVます nghĩa là gì?', N'Không làm V', N'Làm V rồi sau đó làm V', N'Làm V thường xuyên', N'Làm V trong quá khứ', 'B'),
(N'おきて、それからあさごはんを（　　　）。', N'たべる', N'たべます', N'たべたい', N'たべました', 'B'),
(N'どうやってVますか nghĩa là gì?', N'Làm cách nào để V?', N'Tại sao V?', N'Bao giờ V?', N'Ở đâu V?', 'A'),
(N'どうやってきっぷを（　　　）か。', N'かう', N'かいます', N'かった', N'かいたい', 'B'),
(N'私は音楽を（　　　）ことが好きです。', N'ききます', N'きく', N'きいて', N'きいた', 'B'),
(N'彼はダンスを（　　　）ことが好きです。', N'します', N'する', N'した', N'して', 'B'),
(N'私は週末によく映画を（　　　）。', N'みる', N'みます', N'みました', N'みたい', 'B'),
(N'彼はときどき海へ（　　　）。', N'いく', N'いきます', N'いった', N'いきたい', 'B'),
(N'私は日本語を話すことが（　　　）。', N'します', N'できます', N'あります', N'います', 'B'),
(N'私はピアノをひくことが（　　　）。', N'しました', N'できます', N'します', N'ありました', 'B'),
(N'私はあまりスポーツを（　　　）。', N'します', N'しません', N'しました', N'したい', 'B'),
(N'彼はぜんぜんコーヒーを（　　　）。', N'のみます', N'のみません', N'のみました', N'のみたい', 'B'),
(N'週末にジョギングをして、それから友だちと（　　　）。', N'あう', N'あいます', N'あった', N'あいたい', 'B'),
(N'私はうちへ帰って、それからテレビを（　　　）。', N'みる', N'みます', N'みたい', N'みました', 'B');