-- PHẦN 1 (30 câu đầu)
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「漫画」まんが nghĩa là gì?', N'Tiểu thuyết', N'Truyện tranh', N'Phim', N'Bài hát', 'B'),
(N'「小説」しょうせつ nghĩa là gì?', N'Tiểu thuyết', N'Truyện tranh', N'Báo', N'Kế hoạch', 'A'),
(N'「切手」きって nghĩa là gì?', N'Bánh kẹo', N'Tem', N'Ly', N'Thư pháp', 'B'),
(N'「クラシック」 là gì?', N'Nhạc pop', N'Nhạc cổ điển', N'Phim hành động', N'Kịch', 'B'),
(N'「ポップス」 nghĩa là gì?', N'Nhạc cổ điển', N'Nhạc pop', N'Nhạc dân ca', N'Nhạc rock', 'B'),
(N'「最近」さいきん nghĩa là gì?', N'Luôn luôn', N'Gần đây', N'Đặc biệt', N'Chỉ', 'B'),
(N'「特に」とくに nghĩa là gì?', N'Đặc biệt', N'Thường', N'Không bao giờ', N'Chỉ', 'A'),
(N'「いつも」 nghĩa là gì?', N'Thỉnh thoảng', N'Luôn luôn', N'Ít khi', N'Chưa từng', 'B'),
(N'「ときどき」 nghĩa là gì?', N'Luôn luôn', N'Thỉnh thoảng', N'Thường xuyên', N'Hoàn toàn', 'B'),
(N'「あまり～ません」 nghĩa là gì?', N'Rất', N'Hoàn toàn không', N'Không ~ lắm', N'Chỉ', 'C'),
(N'「全然～ません」ぜんぜん nghĩa là gì?', N'Không ~ lắm', N'Thường', N'Hoàn toàn không', N'Đôi khi', 'C'),
(N'「～冊」さつ dùng để đếm gì?', N'Ly nước', N'Người', N'Sách', N'Xe', 'C'),
(N'「～回」かい nghĩa là gì?', N'Tuần', N'Lần', N'Năm', N'Tháng', 'B'),
(N'「～杯」はい dùng để đếm gì?', N'Sách', N'Ly/cốc', N'Xe', N'Nhà', 'B'),
(N'「～本」ほん dùng để đếm gì?', N'Vật dài', N'Người', N'Sách', N'Phim', 'A'),
(N'泳ぎます （およぎます） thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'A'),
(N'食べます thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'B'),
(N'します thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Không nhóm nào', 'C'),
(N'来ます → thể từ điển là gì?', N'くりる', N'くる', N'きる', N'くます', 'B'),
(N'見ます → thể từ điển là gì?', N'見る', N'見う', N'見ぐ', N'見す', 'A'),
(N'書きます （かきます） → thể từ điển là gì?', N'書ぐ', N'書く', N'書る', N'書す', 'B'),
(N'私のしゅみは本を読むことです。 nghĩa là gì?', N'Tôi đọc sách', N'Sở thích là đọc sách', N'Tôi thích sách', N'Tôi mua sách', 'B'),
(N'Cấu trúc nói về sở thích là gì?', N'Vますことです', N'Vることです', N'Vたことです', N'Vないことです', 'B'),
(N'Cấu trúc diễn đạt khả năng là gì?', N'Vることができます', N'Vますことです', N'Vないことです', N'Vたことです', 'A'),
(N'「できます」 nghĩa là gì?', N'Làm', N'Biết', N'Có thể', N'Muốn', 'C'),
(N'「なかなか～できません」 nghĩa là gì?', N'Rất có thể', N'Khó mà có thể', N'Chắc chắn', N'Luôn luôn', 'B'),
(N'一週間に一回映画を見ます。 nghĩa là gì?', N'Mỗi ngày xem phim', N'Một tuần xem phim một lần', N'Một tháng xem phim', N'Hai lần một tuần', 'B'),
(N'「運転します」うんてんします nghĩa là gì?', N'Đi bộ', N'Lái xe', N'Ngủ', N'Viết', 'B'),
(N'「参加します」さんかします nghĩa là gì?', N'Tham gia', N'Rời khỏi', N'Chạy', N'Học', 'A'),
(N'「予約します」よやくします nghĩa là gì?', N'Thanh toán', N'Đặt trước', N'Vào', N'Ra', 'B');

-- PHẦN 2 (Câu 31–60)
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「お菓子」おかし nghĩa là gì?', N'Tem', N'Bánh kẹo', N'Tiểu thuyết', N'Kế hoạch', 'B'),
(N'「ドラマ」 nghĩa là gì?', N'Phim truyền hình', N'Phim hoạt hình', N'Tin tức', N'Trò chơi', 'A'),
(N'「プール」 nghĩa là gì?', N'Công viên', N'Hồ bơi', N'Bãi biển', N'Rạp phim', 'B'),
(N'「つり」 nghĩa là gì?', N'Vẽ tranh', N'Câu cá', N'Chạy bộ', N'Leo núi', 'B'),
(N'「小説」 đọc là gì?', N'しょうせつ', N'しょうさい', N'しょうけつ', N'しょうれつ', 'A'),
(N'「漫画」 đọc là gì?', N'まんげ', N'まんが', N'まんこ', N'まんかい', 'B'),
(N'「切手」 đọc là gì?', N'きりて', N'きって', N'きて', N'きっで', 'B'),
(N'「教室」きょうしつ nghĩa là gì?', N'Câu lạc bộ', N'Lớp học', N'Văn phòng', N'Sân vận động', 'B'),
(N'「書道」しょどう nghĩa là gì?', N'Vẽ tranh', N'Thư pháp', N'Âm nhạc', N'Khiêu vũ', 'B'),
(N'「ダンス」 nghĩa là gì?', N'Hát', N'Khiêu vũ', N'Chạy', N'Bơi', 'B'),
(N'「イベント」 nghĩa là gì?', N'Cuộc thi', N'Sự kiện', N'Lễ hội truyền thống', N'Kế hoạch', 'B'),
(N'「コンテスト」 nghĩa là gì?', N'Sự kiện', N'Cuộc thi', N'Cuộc họp', N'Lễ cưới', 'B'),
(N'「上手に」じょうず nghĩa là gì?', N'Chậm', N'Giỏi, thành thạo', N'Nhanh', N'Ít', 'B'),
(N'「すごい」 nghĩa là gì?', N'Tuyệt vời', N'Bình thường', N'Chậm', N'Tệ', 'A'),
(N'「住所」じゅうしょ nghĩa là gì?', N'Số điện thoại', N'Địa chỉ', N'Tên', N'Tuổi', 'B'),
(N'「電話番号」でんわばんごう nghĩa là gì?', N'Địa chỉ', N'Số điện thoại', N'Số phòng', N'Số nhà', 'B'),
(N'「宿題」しゅくだい nghĩa là gì?', N'Bài thi', N'Bài tập về nhà', N'Công việc', N'Kế hoạch', 'B'),
(N'「受付」うけつけ nghĩa là gì?', N'Nhà bếp', N'Quầy lễ tân', N'Cửa hàng', N'Bến xe', 'B'),
(N'「払います」はらいます nghĩa là gì?', N'Nhận', N'Trả tiền', N'Cho xem', N'Vào', 'B'),
(N'「見せます」 nghĩa là gì?', N'Nhìn', N'Cho xem', N'Xem', N'Nghe', 'B'),
(N'「降ります」おります nghĩa là gì?', N'Lên xe', N'Xuống xe', N'Đi bộ', N'Chạy', 'B'),
(N'「入ります」 thể từ điển là gì?', N'入る', N'入れる', N'入りる', N'入す', 'A'),
(N'「乗ります」のります: lên | thể từ điển là gì?', N'乗る', N'乗れる', N'乗す', N'乗りる', 'A'),
(N'「集めます」あつめます: thu thập | thể từ điển là gì?', N'集む', N'集める', N'集まる', N'集ぐ', 'B'),
(N'「習います」ならいます: học | thể từ điển là gì?', N'習う', N'習える', N'習す', N'習ぐ', 'A'),
(N'「運転します」うんてんします thể từ điển là gì?', N'運転す', N'運転する', N'運転る', N'運転ます', 'B'),
(N'Câu nào đúng về tần suất?', N'一週間一回映画を見ます。', N'一週間に一回映画を見ます。', N'一週間を一回映画を見ます。', N'一週間がいっかい映画を見ます。', 'B'),
(N'Cấu trúc đúng của khả năng?', N'日本語を話しますことができます。', N'日本語を話すことができます。', N'日本語を話すができます。', N'日本語を話しますができます。', 'B'),
(N'「だけ」 nghĩa là gì?', N'Nhưng', N'Chỉ', N'Và', N'Hoặc', 'B'),
(N'「でも」 nghĩa là gì?', N'Chỉ', N'Nhưng', N'Luôn luôn', N'Không bao giờ', 'B');

-- PHẦN 3 (Câu 61–90)
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「外国」がいこく nghĩa là gì?', N'Trong nước', N'Nước ngoài', N'Quê hương', N'Thành phố', 'B'),
(N'「外国語」がいこくご nghĩa là gì?', N'Ngôn ngữ địa phương', N'Ngoại ngữ', N'Tiếng Nhật', N'Tiếng mẹ đẻ', 'B'),
(N'「外国人」がいこくじん nghĩa là gì?', N'Người Nhật', N'Người nước ngoài', N'Học sinh', N'Giáo viên', 'B'),
(N'「海外」かいがい nghĩa là gì?', N'Trong nước', N'Hải ngoại', N'Biển', N'Thành phố', 'B'),
(N'「旅行」りょこう nghĩa là gì?', N'Học tập', N'Du lịch', N'Làm việc', N'Thi đấu', 'B'),
(N'「海」うみ nghĩa là gì?', N'Sông', N'Biển', N'Hồ', N'Núi', 'B'),
(N'「海水」かいすい nghĩa là gì?', N'Nước suối', N'Nước biển', N'Nước nóng', N'Nước lạnh', 'B'),
(N'「映画」えいが nghĩa là gì?', N'Âm nhạc', N'Phim', N'Kế hoạch', N'Bài hát', 'B'),
(N'「計画」けいかく nghĩa là gì?', N'Kỳ nghỉ', N'Kế hoạch', N'Sự kiện', N'Cuộc thi', 'B'),
(N'「音楽」おんがく nghĩa là gì?', N'Âm thanh', N'Âm nhạc', N'Bài hát', N'Tiếng ồn', 'B'),
(N'「楽しい」 たのしいnghĩa là gì?', N'Buồn', N'Vui vẻ', N'Khó', N'Chán', 'B'),
(N'「歌う」うたう nghĩa là gì?', N'Nghe', N'Hát', N'Viết', N'Đọc', 'B'),
(N'「国歌」こっか nghĩa là gì?', N'Dân ca', N'Quốc ca', N'Nhạc pop', N'Nhạc rock', 'B'),
(N'「車」くるま nghĩa là gì?', N'Tàu', N'Xe hơi', N'Máy bay', N'Xe đạp', 'B'),
(N'「家の外」いえのそと nghĩa là gì?', N'Trong nhà', N'Bên ngoài nhà', N'Sau nhà', N'Trước nhà', 'B'),
(N'辞書形 じしょけ là gì?', N'Thể quá khứ', N'Thể lịch sự', N'Thể từ điển', N'Thể phủ định', 'C'),
(N'Vます chuyển sang Vる gọi là gì?', N'Thể lịch sự', N'Thể khả năng', N'Thể từ điển', N'Thể mệnh lệnh', 'C'),
(N'Động từ nhóm 3 gồm những động từ nào?', N'食べます・見ます', N'来ます・します', N'書きます・読みます', N'泳ぎます・遊びます', 'B'),
(N'食べます → thể từ điển?', N'食ぶ', N'食べる', N'食ぐ', N'食す', 'B'),
(N'読みます → thể từ điển?', N'読む', N'読みる', N'読ぶ', N'読す', 'A'),
(N'遊びます あそびます: chơi | → thể từ điển?', N'遊ぶ', N'遊びる', N'遊む', N'遊す', 'A'),
(N'話します → thể từ điển?', N'話す', N'話る', N'話ぐ', N'話う', 'A'),
(N'待ちます まちます: đợi → thể từ điển?', N'待つ', N'待ちる', N'待す', N'待む', 'A'),
(N'死にます しにます: chết → thể từ điển?', N'死ぬ', N'死にる', N'死む', N'死す', 'A'),
(N'飲みます → thể từ điển?', N'飲ぶ', N'飲む', N'飲る', N'飲す', 'B'),
(N'帰ります かえります: về → thể từ điển?', N'帰う', N'帰る', N'帰りる', N'帰む', 'B'),
(N'Câu nào đúng?', N'私は漫画を読むことです。', N'私のしゅみは漫画を読むことです。', N'私は漫画を読むができます。', N'私の漫画は読むことです。', 'B'),
(N'「Vることです」 dùng để diễn đạt gì?', N'Khả năng', N'Mệnh lệnh', N'Sở thích', N'Quá khứ', 'C'),
(N'Câu nào đúng khi nói khả năng?', N'日本語を話すことができます。', N'日本語を話しますことができます。', N'日本語を話すができます。', N'日本語を話しますができます。', 'A'),
(N'「なかなか日本語を話すことができません」 nghĩa là gì?', N'Nói tiếng Nhật rất tốt', N'Thường nói tiếng Nhật', N'Khó mà nói được tiếng Nhật', N'Luôn nói tiếng Nhật', 'C');

--PHẦN 4 (Câu 91–120):
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「～年」 dùng để đếm gì?', N'Ngày', N'Tuần', N'Năm', N'Tháng', 'C'),
(N'「～か月」 nghĩa là gì?', N'~ năm', N'~ tháng', N'~ tuần', N'~ ngày', 'B'),
(N'「～週間」 nghĩa là gì?', N'~ tháng', N'~ tuần', N'~ năm', N'~ giờ', 'B'),
(N'「～日」 đọc là gì?', N'～にち', N'～ひ', N'～び', N'～げつ', 'A'),
(N'「最近」 thường dùng với thì nào?', N'Quá khứ xa', N'Hiện tại/gần đây', N'Tương lai xa', N'Mệnh lệnh', 'B'),
(N'「よく」 dùng để diễn đạt gì?', N'Hoàn toàn không', N'Tần suất cao', N'Mệnh lệnh', N'Phủ định', 'B'),
(N'Câu nào đúng?', N'私はときどき映画を見ます。', N'私はときどき映画を見ません。 (luôn luôn)', N'私はときどき映画が見ます。', N'私はときどき映画を見ますか。', 'A'),
(N'「あまり」 đi với dạng nào?', N'Thể khẳng định', N'Thể phủ định', N'Thể mệnh lệnh', N'Thể quá khứ', 'B'),
(N'Câu đúng với 「全然」?', N'全然食べます。', N'全然食べません。', N'全然食べました。', N'全然食べる。', 'B'),
(N'「だけ」 đặt ở đâu?', N'Sau danh từ', N'Trước động từ', N'Đầu câu', N'Cuối câu bắt buộc', 'A'),
(N'「được」 thường dùng để làm gì?', N'Liệt kê', N'So sánh', N'Nối câu trái nghĩa', N'Hỏi', 'C'),
(N'「泳ぐ」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'A'),
(N'「見る」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'B'),
(N'「する」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Không nhóm nào', 'C'),
(N'「来る」 đọc là gì?', N'らいる', N'くる', N'きる', N'くりる', 'B'),
(N'「書きます」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'A'),
(N'「集める」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'B'),
(N'Cấu trúc: Thời gian + に + số lần dùng để?', N'Chỉ địa điểm', N'Chỉ tần suất', N'Chỉ nguyên nhân', N'Chỉ mục đích', 'B'),
(N'一か月に三回日本語を勉強します。 nghĩa là gì?', N'Một tháng học 3 lần', N'Một tuần học 3 lần', N'Ba tháng học 1 lần', N'Mỗi ngày học', 'A'),
(N'「参加する」 nghĩa là gì?', N'Rời đi', N'Tham gia', N'Học', N'Dạy', 'B'),
(N'「申し込む」 nghĩa là gì?', N'Thanh toán', N'Đăng ký', N'Rời khỏi', N'Nhìn', 'B'),
(N'「入る」 nghĩa là gì?', N'Ra ngoài', N'Vào', N'Đứng', N'Ngồi', 'B'),
(N'「降りる」 nghĩa là gì?', N'Lên xe', N'Xuống xe', N'Chạy', N'Đi bộ', 'B'),
(N'「見せる」 nghĩa là gì?', N'Nhìn', N'Cho xem', N'Thấy', N'Nghe', 'B'),
(N'Câu nào đúng về sở thích?', N'私のしゅみは映画を見ることです。', N'私は映画を見ることです。', N'私の映画は見ることです。', N'映画は私のしゅみことです。', 'A'),
(N'Câu hỏi đúng về sở thích?', N'あなたは何しゅみですか。', N'あなたのしゅみは何ですか。', N'あなたしゅみは何です。', N'あなたの何はしゅみですか。', 'B'),
(N'「Vることができます」 dùng để?', N'Diễn tả sở thích', N'Diễn tả khả năng', N'Diễn tả quá khứ', N'Diễn tả mệnh lệnh', 'B'),
(N'毎日日本語を話すことができます。 nghĩa là gì?', N'Mỗi ngày nói tiếng Nhật', N'Có thể nói tiếng Nhật mỗi ngày', N'Không nói tiếng Nhật', N'Đã nói tiếng Nhật', 'B'),
(N'なかなか会うことができません。 nghĩa là gì?', N'Thường gặp', N'Không bao giờ gặp', N'Khó mà gặp được', N'Luôn gặp', 'C'),
(N'「どうやって」 nghĩa là gì?', N'Ở đâu', N'Bao nhiêu', N'Làm thế nào', N'Khi nào', 'C');

--PHẦN 5 (Câu 121–150):
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'「大好き」 nghĩa là gì?', N'Không thích', N'Rất thích', N'Ghét', N'Bình thường', 'B'),
(N'「大好物」 nghĩa là gì?', N'Món ăn đắt tiền', N'Món ăn truyền thống', N'Món khoái khẩu', N'Món mới', 'C'),
(N'「好き(な)」 là loại từ gì?', N'Động từ', N'Tính từ な', N'Tính từ い', N'Danh từ', 'B'),
(N'「楽しい」 là loại từ gì?', N'Tính từ い', N'Tính từ な', N'Động từ', N'Danh từ', 'A'),
(N'「音」 nghĩa là gì?', N'Ánh sáng', N'Âm thanh', N'Hình ảnh', N'Mùi vị', 'B'),
(N'「音読み」 nghĩa là gì?', N'Âm Kun', N'Âm On', N'Âm Việt', N'Âm Hàn', 'B'),
(N'「短歌」 nghĩa là gì?', N'Bài hát dài', N'Thơ ngắn', N'Nhạc pop', N'Kịch', 'B'),
(N'「社外」 nghĩa là gì?', N'Trong công ty', N'Ngoài công ty', N'Ngoài nước', N'Trong nhà', 'B'),
(N'「家の外」 nghĩa là gì?', N'Trong nhà', N'Bên ngoài nhà', N'Sau nhà', N'Trước nhà', 'B'),
(N'「海外」 có nghĩa gần nhất với từ nào?', N'外国', N'海水', N'旅行', N'住所', 'A'),
(N'「旅行」 gồm những chữ Hán nào?', N'旅 + 行', N'外 + 国', N'音 + 楽', N'計 + 画', 'A'),
(N'「映画」 gồm những chữ Hán nào?', N'音 + 楽', N'映 + 画', N'外 + 国', N'海 + 水', 'B'),
(N'「計画」 đọc là gì?', N'けいが', N'けいかく', N'けいご', N'けいこう', 'B'),
(N'「外国語」 đọc là gì?', N'がいこくご', N'がいごくご', N'がいこっご', N'がいくご', 'A'),
(N'「電話番号」 nghĩa là gì?', N'Số nhà', N'Số điện thoại', N'Số phòng', N'Mã số sinh viên', 'B'),
(N'「カードを作ります」 nghĩa là gì?', N'Mua thẻ', N'Làm thẻ', N'Bán thẻ', N'Hủy thẻ', 'B'),
(N'「図書館」 nghĩa là gì?', N'Rạp phim', N'Thư viện', N'Trường học', N'Nhà ga', 'B'),
(N'Câu nào đúng?', N'図書館のカードを作ります。', N'図書館をカード作ります。', N'カードの図書館を作ります。', N'図書館カードをの作ります。', 'A'),
(N'「住所を言います」 nghĩa là gì?', N'Viết địa chỉ', N'Nói địa chỉ', N'Xem địa chỉ', N'Xóa địa chỉ', 'B'),
(N'「電話番号を見せます」 nghĩa là gì?', N'Gọi điện thoại', N'Cho xem số điện thoại', N'Đổi số điện thoại', N'Ghi số điện thoại', 'B'),
(N'「払う」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'A'),
(N'「見せる」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'B'),
(N'「できる」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Bất quy tắc', 'B'),
(N'「来る」 thuộc nhóm nào?', N'Nhóm 1', N'Nhóm 2', N'Nhóm 3', N'Không nhóm nào', 'C'),
(N'Câu nào đúng?', N'私は日本語ができます。', N'私は日本語をできます。', N'私は日本語にできます。', N'私は日本語でできます。', 'A'),
(N'「スキーができます」 nghĩa là gì?', N'Thích trượt tuyết', N'Biết trượt tuyết', N'Muốn trượt tuyết', N'Đang trượt tuyết', 'B'),
(N'「一週間に三回」 nghĩa là gì?', N'Ba tuần một lần', N'Một tuần ba lần', N'Ba tháng một lần', N'Ba năm một lần', 'B'),
(N'Câu nào đúng?', N'私はあまり映画を見ます。', N'私はあまり映画を見ません。', N'私は全然映画を見ます。', N'私は全然映画を見ました。', 'B'),
(N'「なかなか日本へ行くことができません」 nghĩa là gì?', N'Thường đi Nhật', N'Không bao giờ đi Nhật', N'Khó mà đi Nhật', N'Đã đi Nhật', 'C'),
(N'「どうやって学校へ行きますか」 nghĩa là gì?', N'Khi nào đến trường?', N'Đi đâu?', N'Đi đến trường bằng cách nào?', N'Tại sao đi học?', 'C');

--PHẦN 6 (151–180)
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'Động từ nào thuộc nhóm 2?', N'話します', N'食べます', N'書きます', N'泳ぎます', 'B'),
(N'Động từ nào thuộc nhóm 1?', N'見ます', N'起きます', N'帰ります', N'できます', 'C'),
(N'「帰ります」 thể từ điển là gì?', N'帰りる', N'帰う', N'帰る', N'帰む', 'C'),
(N'「飲みます」 đổi sang thể từ điển?', N'飲ぶ', N'飲む', N'飲る', N'飲す', 'B'),
(N'「死にます」 đổi sang thể từ điển?', N'死ぬ', N'死ぶ', N'死む', N'死る', 'A'),
(N'「遊びます」 đổi sang thể từ điển?', N'遊ぶ', N'遊びる', N'遊む', N'遊る', 'A'),
(N'「待ちます」 đổi sang thể từ điển?', N'待つ', N'待ちる', N'待す', N'待ぬ', 'A'),
(N'「話します」 đổi sang thể từ điển?', N'話る', N'話す', N'話ぶ', N'話む', 'B'),
(N'Nhóm 3 gồm?', N'する・くる', N'食べる・見る', N'書く・読む', N'泳ぐ・遊ぶ', 'A'),
(N'「できる」 thuộc nhóm?', '1', '2', '3', N'Bất quy tắc riêng', 'B'),
(N'Động từ nào KHÔNG phải nhóm 2?', N'見ます', N'食べます', N'起きます', N'帰ります', 'D'),
(N'Quy tắc nhóm 2?', N'Bỏ ます + る', N'Đổi sang う', N'Đổi sang す', N'Giữ nguyên', 'A'),
(N'Quy tắc nhóm 1 (～みます)?', '→ む', '→ る', '→ ぶ', '→ ぬ', 'A'),
(N'Quy tắc nhóm 1 (～びます)?', '→ む', '→ ぬ', '→ ぶ', '→ る', 'C'),
(N'Quy tắc nhóm 1 (～にます)?', '→ ぶ', '→ ぬ', '→ む', '→ つ', 'B'),
(N'Quy tắc nhóm 1 (～ちます)?', '→ つ', '→ る', '→ ぬ', '→ ぶ', 'A'),
(N'Quy tắc nhóm 1 (～します)?', '→ す', '→ る', '→ つ', '→ ぶ', 'A'),
(N'Quy tắc nhóm 1 (～きます)?', '→ く', '→ ぐ', '→ る', '→ む', 'A'),
(N'Quy tắc nhóm 1 (～ぎます)?', '→ ぐ', '→ く', '→ む', '→ ぶ', 'A'),
(N'辞書形 dùng để làm gì?', N'Nối câu', N'Làm mệnh đề danh hóa', N'Chia quá khứ', N'Mệnh lệnh', 'B'),
(N'Cấu trúc danh hóa động từ?', N'Vますこと', N'Vること', N'Vないこと', N'Vたこと', 'B'),
(N'「読むこと」 là gì?', N'Động từ', N'Danh từ hóa', N'Tính từ', N'Phó từ', 'B'),
(N'Câu nào đúng?', N'本を読むことが好きです。', N'本を読むが好きです。', N'本を読むこと好きです。', N'本読むことが好きです。', 'A'),
(N'「日本語を話すことができます」 dùng trợ từ gì cho khả năng?', N'を', N'に', N'が', N'で', 'C'),
(N'Trong khả năng, tân ngữ thường đi với?', N'を', N'が', N'に', N'へ', 'B'),
(N'Câu đúng?', N'私はピアノをひくことができます。', N'私はピアノがひくことができます。', N'私はピアノにひくことができます。', N'私はピアノでひくことができます。', 'A'),
(N'「一日に三回」 chỉ gì?', N'Địa điểm', N'Tần suất', N'Nguyên nhân', N'So sánh', 'B'),
(N'Trợ từ trong tần suất?', N'が', N'を', N'に', N'で', 'C'),
(N'Câu đúng?', N'一週間に二回運動します。', N'一週間が二回運動します。', N'一週間を二回運動します。', N'一週間で二回運動します。', 'A'),
(N'「だけ」 đứng sau?', N'Động từ', N'Danh từ', N'Tính từ', N'Phó từ', 'B');