USE quiz_db;
GO
--BÀI 8: TỪ VỰNG PHẦN 1
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'りょうしん nghĩa là gì?', N'Anh trai', N'Bố mẹ (của mình)', N'Con trai', N'Bạn bè', 'B'),
(N'ちち nghĩa là gì?', N'Bố (của mình)', N'Mẹ (của mình)', N'Ông', N'Chú', 'A'),
(N'はは nghĩa là gì?', N'Bà', N'Chị gái', N'Mẹ (của mình)', N'Cô', 'C'),
(N'きょうだい nghĩa là gì?', N'Bố mẹ', N'Anh chị em', N'Con cái', N'Bạn học', 'B'),
(N'あに nghĩa là gì?', N'Em trai', N'Bố', N'Anh trai (của mình)', N'Chồng', 'C'),
(N'あね nghĩa là gì?', N'Chị gái (của mình)', N'Em gái', N'Mẹ', N'Vợ', 'A'),
(N'おとうと nghĩa là gì?', N'Con trai', N'Em trai (của mình)', N'Anh trai', N'Cháu trai', 'B'),
(N'いもうと nghĩa là gì?', N'Chị gái', N'Con gái', N'Em gái (của mình)', N'Cháu gái', 'C'),
(N'おっと nghĩa là gì?', N'Bạn trai', N'Chồng (của mình)', N'Vợ (của mình)', N'Anh trai', 'B'),
(N'つま nghĩa là gì?', N'Chị gái', N'Vợ (của mình)', N'Mẹ', N'Chồng (của mình)', 'B'),
(N'こども nghĩa là gì?', N'Con (của mình)', N'Bố', N'Mẹ', N'Anh trai', 'A'),
(N'むすこ nghĩa là gì?', N'Con gái', N'Anh trai', N'Con trai (của mình)', N'Em trai', 'C'),
(N'むすめ nghĩa là gì?', N'Con trai', N'Chị gái', N'Em gái', N'Con gái (của mình)', 'D'),
(N'おとうさん nghĩa là gì?', N'Ông nội', N'Bố (của người khác)', N'Bố (của mình)', N'Chú', 'B'),
(N'おかあさん nghĩa là gì?', N'Mẹ (của người khác)', N'Bà ngoại', N'Mẹ (của mình)', N'Cô', 'A'),
(N'おにいさん nghĩa là gì?', N'Anh trai (của người khác)', N'Em trai', N'Bố', N'Bạn', 'A'),
(N'おねえさん nghĩa là gì?', N'Bạn', N'Chị gái (của người khác)', N'Em gái', N'Mẹ', 'B'),
(N'おとうとさん nghĩa là gì?', N'Con trai', N'Anh trai', N'Em trai (của người khác)', N'Cháu trai', 'C'),
(N'いもうとさん nghĩa là gì?', N'Chị gái', N'Em gái (của người khác)', N'Con gái', N'Cháu gái', 'B'),
(N'おこさん nghĩa là gì?', N'Con (của người khác)', N'Cháu', N'Bạn', N'Con (của mình)', 'A'),
(N'ペット nghĩa là gì?', N'Động vật hoang dã', N'Thú nuôi', N'Cây', N'Đồ chơi', 'B'),
(N'ねこ nghĩa là gì?', N'Con mèo', N'Con chó', N'Con chim', N'Con cá', 'A'),
(N'ピアノ nghĩa là gì?', N'Đàn guitar', N'Đàn piano', N'Đàn violin', N'Trống', 'B'),
(N'いしゃ nghĩa là gì?', N'Giáo viên', N'Kỹ sư', N'Bác sĩ', N'Sinh viên', 'C'),
(N'こうこうせい nghĩa là gì?', N'Học sinh tiểu học', N'Học sinh cấp ba', N'Sinh viên', N'Giáo viên', 'B'),
(N'だいがくせい nghĩa là gì?', N'Sinh viên đại học', N'Học sinh cấp ba', N'Giáo viên', N'Bác sĩ', 'A'),
(N'～にん dùng để đếm gì?', N'Con vật', N'Người', N'Đồ vật', N'Xe', 'B'),
(N'～ひき dùng để đếm gì?', N'Người', N'Nhà', N'Con vật nhỏ', N'Sách', 'C'),
(N'すみます nghĩa là gì?', N'Sống, sinh sống', N'Ăn', N'Uống', N'Đi', 'A'),
(N'います nghĩa là gì?', N'Có (đồ vật)', N'Có (người, động vật)', N'Đi', N'Đến', 'B'),
(N'どくしん nghĩa là gì?', N'Có (người, động vật)', N'Độc thân', N'Đi', N'Đến', 'B');

--BÀI 8: TỪ VỰNG PHẦN 2
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'ごしゅじん nghĩa là gì?', N'Chồng (của mình)', N'Chồng (của người khác)', N'Anh trai', N'Bạn trai', 'B'),
(N'おくさん nghĩa là gì?', N'Vợ (của mình)', N'Chị gái', N'Vợ (của người khác)', N'Mẹ', 'C'),
(N'せんぱい nghĩa là gì?', N'Bạn cùng lớp', N'Tiền bối, người đi trước', N'Giáo viên', N'Người mới', 'B'),
(N'こうはい nghĩa là gì?', N'Tiền bối', N'Giáo viên', N'Hậu bối, đàn em', N'Bạn thân', 'C'),
(N'うさぎ nghĩa là gì?', N'Con mèo', N'Con thỏ', N'Con chó', N'Con chim', 'B'),
(N'からだ nghĩa là gì?', N'Đầu', N'Cơ thể, sức khỏe', N'Mặt', N'Tay', 'B'),
(N'あし nghĩa là gì?', N'Tay', N'Mắt', N'Chân', N'Mũi', 'C'),
(N'かお nghĩa là gì?', N'Đầu', N'Mặt, khuôn mặt', N'Tóc', N'Tai', 'B'),
(N'かみ nghĩa là gì?', N'Mũi', N'Miệng', N'Mắt', N'Tóc', 'D'),
(N'くち nghĩa là gì?', N'Miệng', N'Mũi', N'Mắt', N'Tai', 'A'),
(N'はな nghĩa là gì?', N'Miệng', N'Mũi', N'Mắt', N'Tai', 'B'),
(N'め nghĩa là gì?', N'Miệng', N'Mũi', N'Mắt', N'Tai', 'C'),
(N'みみ nghĩa là gì?', N'Mắt', N'Tai', N'Mũi', N'Miệng', 'B'),
(N'あたまがいい nghĩa là gì?', N'Lười biếng', N'Thông minh', N'Chậm chạp', N'Yếu', 'B'),
(N'かっこいい nghĩa là gì?', N'Xấu', N'Già', N'Bảnh bao, đẹp trai', N'Thấp', 'C'),
(N'かわいい nghĩa là gì?', N'Đáng sợ', N'Đáng yêu, dễ thương', N'Khó chịu', N'Xấu xí', 'B'),
(N'せがたかい nghĩa là gì?', N'Thấp', N'Gầy', N'Mập', N'Cao (dáng người)', 'D'),
(N'ながい nghĩa là gì?', N'Ngắn', N'Cao', N'Dài', N'Thấp', 'C'),
(N'みじかい nghĩa là gì?', N'Ngắn', N'Dài', N'Cao', N'Thấp', 'A'),
(N'やさしい nghĩa là gì?', N'Khó tính', N'Nóng tính', N'Hiền lành', N'Lạnh lùng', 'C'),
(N'くろい nghĩa là gì?', N'Trắng', N'Đen', N'Xanh', N'Đỏ', 'B'),
(N'しろい nghĩa là gì?', N'Đen', N'Trắng', N'Xanh', N'Đỏ', 'B'),
(N'ちゃいろい nghĩa là gì?', N'Màu đỏ', N'Màu nâu', N'Màu xanh', N'Màu vàng', 'B'),
(N'げんき（な） nghĩa là gì?', N'Yếu', N'Khỏe mạnh', N'Mệt mỏi', N'Ốm', 'B'),
(N'しんせつ（な） nghĩa là gì?', N'Ác', N'Lười', N'Tốt bụng', N'Ích kỷ', 'C'),
(N'まじめ（な） nghĩa là gì?', N'Lười biếng', N'Nghịch ngợm', N'Chăm chỉ, cần mẫn', N'Chậm chạp', 'C'),
(N'じょうず（な） nghĩa là gì?', N'Kém', N'Giỏi', N'Yếu', N'Tệ', 'B'),
(N'へた（な） nghĩa là gì?', N'Giỏi', N'Thông minh', N'Kém', N'Chăm chỉ', 'C');

--BÀI 8: TỪ VỰNG PHẦN 3
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'カード nghĩa là gì?', N'Thư', N'Thẻ / thiệp', N'Sách', N'Vé', 'B'),
(N'かさ nghĩa là gì?', N'Mũ', N'Áo khoác', N'Ô, cái ô', N'Khăn', 'C'),
(N'（お）かね nghĩa là gì?', N'Tiền', N'Thư', N'Quà', N'Sách', 'A'),
(N'くつした nghĩa là gì?', N'Giày', N'Đôi tất', N'Áo', N'Quần', 'B'),
(N'じしょ nghĩa là gì?', N'Sách giáo khoa', N'Truyện', N'Từ điển', N'Tạp chí', 'C'),
(N'チョコレート nghĩa là gì?', N'Sô cô la', N'Bánh', N'Kẹo', N'Kem', 'A'),
(N'てがみ nghĩa là gì?', N'Thiệp', N'Thư', N'Tin nhắn', N'Email', 'B'),
(N'ネックレス nghĩa là gì?', N'Nhẫn', N'Bông tai', N'Vòng cổ', N'Đồng hồ', 'C'),
(N'ノート nghĩa là gì?', N'Vở, quyển vở', N'Sách', N'Bút', N'Túi', 'A'),
(N'プレゼント nghĩa là gì?', N'Tiền', N'Quà, món quà', N'Thư', N'Thiệp', 'B'),
(N'メール nghĩa là gì?', N'Thư điện tử (email)', N'Thư tay', N'Cuộc gọi', N'Tin nhắn', 'A'),
(N'そぼ nghĩa là gì?', N'Ông (của mình)', N'Bà (của mình)', N'Mẹ', N'Cô', 'B'),
(N'クリスマス nghĩa là gì?', N'Năm mới', N'Lễ hội', N'Giáng sinh', N'Sinh nhật', 'C'),
(N'けっこんしき nghĩa là gì?', N'Lễ kết hôn', N'Lễ tốt nghiệp', N'Lễ sinh nhật', N'Lễ hội', 'A'),
(N'バレンタインデー nghĩa là gì?', N'Ngày của mẹ', N'Ngày lễ tình nhân', N'Ngày của cha', N'Ngày quốc khánh', 'B'),
(N'なにか nghĩa là gì?', N'Cái gì đó', N'Tất cả', N'Không có gì', N'Mọi người', 'A'),
(N'おくります nghĩa là gì?', N'Nhận', N'Gửi / tiễn', N'Mua', N'Bán', 'B'),
(N'もらいます nghĩa là gì?', N'Tặng', N'Gửi', N'Nhận', N'Mua', 'C'),
(N'あげます nghĩa là gì?', N'Tặng, biếu', N'Nhận', N'Gửi', N'Mượn', 'A'),
(N'くれます nghĩa là gì?', N'Tặng người khác', N'Cho (mình)', N'Nhận', N'Gửi', 'B'),
(N'でんわします nghĩa là gì?', N'Gửi email', N'Gọi điện thoại', N'Viết thư', N'Nhắn tin', 'B'),
(N'もうすぐ nghĩa là gì?', N'Vừa mới', N'Sắp, sắp sửa', N'Đã lâu', N'Đôi khi', 'B'),
(N'よかったですね nghĩa là gì?', N'Tệ quá!', N'Tốt quá nhỉ!', N'Buồn quá!', N'Khó quá!', 'B');

--BÀI 8: KANJI
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'家 (うち・いえ) nghĩa là gì?', N'Trường học', N'Nhà', N'Gia đình', N'Cửa hàng', 'B'),
(N'大家 (おおや) nghĩa là gì?', N'Người thuê nhà', N'Hàng xóm', N'Chủ trọ', N'Bảo vệ', 'C'),
(N'家族 (かぞく) nghĩa là gì?', N'Gia đình', N'Bạn bè', N'Họ hàng', N'Cha mẹ', 'A'),
(N'父 (ちち) nghĩa là gì?', N'Mẹ (của mình)', N'Bố (của mình)', N'Ông', N'Chú', 'B'),
(N'お父さん (おとうさん) nghĩa là gì?', N'Bố (của mình)', N'Bố (của người khác)', N'Ông nội', N'Chú', 'B'),
(N'母 (はは) nghĩa là gì?', N'Mẹ (của mình)', N'Bố (của mình)', N'Bà', N'Cô', 'A'),
(N'お母さん (おかあさん) nghĩa là gì?', N'Mẹ (của mình)', N'Bà ngoại', N'Mẹ (của người khác)', N'Cô', 'C'),
(N'父母 (ふぼ) nghĩa là gì?', N'Ông bà', N'Cha mẹ', N'Anh em', N'Bạn bè', 'B'),
(N'母国語 (ぼこくご) nghĩa là gì?', N'Tiếng Anh', N'Tiếng mẹ đẻ', N'Tiếng Nhật', N'Tiếng nước ngoài', 'B'),
(N'兄 (あに) nghĩa là gì?', N'Em trai', N'Bố', N'Anh trai (của mình)', N'Chú', 'C'),
(N'お兄さん (おにいさん) nghĩa là gì?', N'Anh trai (của người khác)', N'Em trai', N'Bố', N'Bạn', 'A'),
(N'弟 (おとうと) nghĩa là gì?', N'Anh trai', N'Em trai (của mình)', N'Con trai', N'Cháu trai', 'B'),
(N'弟さん (おとうとさん) nghĩa là gì?', N'Anh trai', N'Con trai', N'Em trai (của người khác)', N'Bạn', 'C'),
(N'兄弟 (きょうだい) nghĩa là gì?', N'Cha mẹ', N'Anh chị em', N'Ông bà', N'Bạn bè', 'B'),
(N'姉 (あね) nghĩa là gì?', N'Chị gái (của mình)', N'Em gái', N'Mẹ', N'Cô', 'A'),
(N'お姉さん (おねえさん) nghĩa là gì?', N'Em gái', N'Chị gái (của người khác)', N'Mẹ', N'Bạn', 'B'),
(N'妹 (いもうと) nghĩa là gì?', N'Chị gái', N'Em gái (của mình)', N'Con gái', N'Cháu gái', 'B'),
(N'妹さん (いもうとさん) nghĩa là gì?', N'Em gái (của người khác)', N'Chị gái', N'Con gái', N'Bạn', 'A'),
(N'姉妹 (しまい) nghĩa là gì?', N'Chị em gái', N'Anh em trai', N'Cha mẹ', N'Bạn bè', 'A'),
(N'犬 (いぬ) nghĩa là gì?', N'Con mèo', N'Con chó', N'Con thỏ', N'Con chim', 'B'),
(N'高い (たかい) nghĩa là gì?', N'Cao', N'Thấp', N'Dài', N'Ngắn', 'A'),
(N'高校 (こうこう) nghĩa là gì?', N'Trường đại học', N'Trường cấp ba', N'Trường tiểu học', N'Trường mẫu giáo', 'B'),
(N'高校生 (こうこうせい) nghĩa là gì?', N'Sinh viên đại học', N'Học sinh cấp ba', N'Học sinh tiểu học', N'Giáo viên', 'B'),
(N'短い (みじかい) nghĩa là gì?', N'Dài', N'Ngắn', N'Cao', N'Thấp', 'B'),
(N'短大 (たんだい) nghĩa là gì?', N'Trường đại học', N'Trường cao đẳng', N'Trường cấp ba', N'Trường trung học', 'B'),
(N'長い (ながい) nghĩa là gì?', N'Dài', N'Ngắn', N'Cao', N'Thấp', 'A'),
(N'族長 (ぞくちょう) nghĩa là gì?', N'Tộc trưởng', N'Giám đốc', N'Giáo viên', N'Trưởng lớp', 'A'),
(N'社長 (しゃちょう) nghĩa là gì?', N'Giáo viên', N'Giám đốc công ty', N'Hiệu trưởng', N'Nhân viên', 'B'),
(N'学長 (がくちょう) nghĩa là gì?', N'Giám đốc', N'Hiệu trưởng đại học', N'Giáo viên', N'Sinh viên', 'B'),
(N'校長 (こうちょう) nghĩa là gì?', N'Hiệu trưởng trường học', N'Giáo viên', N'Học sinh', N'Nhân viên', 'A');

--BÀI 8: NGỮ PHÁP
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, correct_answer) VALUES
(N'わたしはパソコン（　）もっています。',N'が',N'を',N'に',N'で','B'),
(N'わたしはホーチミン（　）すんでいます。',N'で',N'を',N'に',N'が','C'),
(N'マリアさんはうた（　）じょうずです。',N'を',N'に',N'が',N'で','C'),
(N'わたしはともだち（　）はなをあげました。',N'を',N'に',N'で',N'が','B'),
(N'わたしはともだち（　）はなをもらいました。',N'で',N'に',N'が',N'を','B'),
(N'マリアさんはかみ（　）ながいです。',N'を',N'が',N'で',N'に','B'),
(N'ミラーさんはにほんご（　）じょうずです。',N'が',N'に',N'を',N'で','A'),
(N'このかばんは（　）ですか。',N'どれ',N'どんな',N'どの',N'なん','A'),
(N'（　）かばんですか。',N'どんな',N'どれ',N'どの',N'なん','C'),
(N'ミラーさんはハンサム（　）しんせつです。',N'くて',N'で',N'に',N'が','B'),
(N'きょうはてんきが（　）です。',N'よい',N'よく',N'いい',N'よかった','C'),
(N'てんきがよく（　）、あついです。',N'で',N'て',N'に',N'が','B'),
(N'わたしはともだちにカードを（　）。',N'もらいます',N'あげます',N'くれます',N'します','B'),
(N'ともだちはわたしにプレゼントを（　）。',N'もらいました',N'あげました',N'くれました',N'しました','C'),
(N'わたしはねこ（　）います。',N'を',N'が',N'に',N'で','B'),
(N'わたし（　）おとうとがいます。',N'が',N'を',N'は',N'に','C'),
(N'マリアさんはせ（　）たかいです。',N'が',N'で',N'を',N'に','A'),
(N'あのひとはとても（　）です。',N'やさしく',N'やさしい',N'やさしで',N'やさし','B'),
(N'わたしはおかね（　）ありません。',N'を',N'が',N'に',N'で','B'),
(N'あのひとはかお（　）きれいです。',N'に',N'で',N'が',N'を','C'),
(N'このねこはみみ（　）ながいです。',N'で',N'が',N'を',N'に','B'),
(N'もうすぐクリスマス（　）です。',N'が',N'に',N'で',N'を','A'),
(N'きのうともだちにメールを（　）。',N'あげました',N'しました',N'もらいました',N'くれました','B'),
(N'ミラーさんはにほんごが（　）。',N'じょうずで',N'じょうずに',N'じょうずを',N'じょうずです','D'),
(N'このひとはとても（　）です。',N'まじめで',N'まじめな',N'まじめに',N'まじめ','B'),
(N'このひとは（　）で、しんせつです。',N'まじめ',N'まじめな',N'まじめで',N'まじめに','C'),
(N'わたしはベトナム（　）すんでいます。',N'が',N'を',N'に',N'で','C'),
(N'ミラーさんはアメリカ（　）きました。',N'で',N'に',N'から',N'を','C'),
(N'このひとはどんな（　）ですか。',N'ひと',N'ところ',N'もの',N'かばん','A'),
(N'きょうは（　）あついです。',N'とても',N'とてもに',N'とてもで',N'とてもを','A'),
(N'マリアさんはかみが（　）。',N'ながいに',N'ながいで',N'ながいを',N'ながいです','D'),
(N'このひとはあたま（　）いいです。',N'が',N'で',N'を',N'に','A'),
(N'（　）ひとですか。',N'どの',N'どんな',N'どれ',N'なに','B'),
(N'ミラーさんは（　）です。',N'こうこう',N'こうこうせい',N'こうこうに',N'こうこうを','B'),
(N'きょうはとても（　）です。',N'さむく',N'さむい',N'さむで',N'さむ','B');