CREATE DATABASE quiz_db;
USE quiz_db;
GO

IF OBJECT_ID('UserResponses', 'U') IS NULL
BEGIN
    CREATE TABLE UserResponses (
        id INT IDENTITY(1,1) PRIMARY KEY,
        question_id INT,
        selected_option VARCHAR(10),
        created_at DATETIME DEFAULT GETDATE()
    );
END

ALTER TABLE QuizQuestions ALTER COLUMN option_a NVARCHAR(MAX);
ALTER TABLE QuizQuestions ALTER COLUMN option_b NVARCHAR(MAX);
ALTER TABLE QuizQuestions ALTER COLUMN option_c NVARCHAR(MAX);
ALTER TABLE QuizQuestions ALTER COLUMN option_d NVARCHAR(MAX);
ALTER TABLE QuizQuestions ALTER COLUMN option_e NVARCHAR(MAX);
ALTER TABLE QuizQuestions ALTER COLUMN option_f NVARCHAR(MAX);
GO

IF OBJECT_ID('QuizQuestions', 'U') IS NULL
BEGIN
    CREATE TABLE QuizQuestions (
        id INT IDENTITY(1,1) PRIMARY KEY,
        question NVARCHAR(MAX),
        option_a NVARCHAR(MAX),
        option_b NVARCHAR(MAX),
        option_c NVARCHAR(MAX),
        option_d NVARCHAR(MAX),
        option_e NVARCHAR(MAX),
        option_f NVARCHAR(MAX),
        correct_answer VARCHAR(10)
    );
END
GO

TRUNCATE TABLE UserResponses;
TRUNCATE TABLE QuizQuestions;
GO

SELECT * FROM QuizQuestions;

--- 2 ANSWER
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, option_e, option_f, correct_answer) VALUES 
('Some stakeholders are customers, such as legal staff, compliance auditors, suppliers, contractors, and venture capitalists', 
 'True', 
 'False', 
 '', 
 '', 
 '', 
 '', 
 'B'),
('Which elements are mandatory in use case?', 
 'Post-condition', 
 'Actors', 
 'Pre-condition', 
 'Name', 
 '', 
 '', 
 'BD'),
('What do product champions do? Choose 2 correct answers.', 
 'They gather requirements from other members of the user classes they represent, and reconcile inconsistencies.', 
 'They serve as the primary interface between members of a single user class and the project''s business analyst.', 
 'They implement the coding standards.', 
 'They write requirements documents.', 
 '', 
 '', 
 'AB'),
('Which of the following tasks are typically performed by a business analyst? Select two.', 
 'Defining business requirements and helping project sponsors express the project''s vision clearly.', 
 'Focusing only on textual documentation and avoiding the use of visual aids like diagrams and prototypes.', 
 'Ensuring that all team members fully understand the requirements being communicated.', 
 'Managing the entire software development life cycle, from inception to deployment.', 
 '', 
 '', 
 'AC'),
('Which of the following statements about reaching agreement on requirements is accurate? Select two.', 
 'Signing off on requirements is an infallible method to prevent any changes later in the project.', 
 'All participants in the requirements approval process must understand what signing off implies.', 
 'The purpose of signing off is to freeze requirements and prevent any future modifications.', 
 'Reaching agreement on requirements ensures that both customers and developers have a shared understanding of project objectives', 
 '', 
 '', 
 'BD'),
('What is the benefit of having a small group representing key areas as decision makers in a project?', 
 'It simplifies the decision-making process by involving only the project manager', 
 'It ensures diverse perspectives from management, customers, business analysis, development, and marketing', 
 'It reduces the need for stakeholder involvement', 
 'It focuses solely on technical specifications', 
 '', 
 '', 
 'B'),
('Which of the following practices should be followed when documenting software requirements? Select two.', 
 'Ensure that each requirement is documented in multiple places to increase visibility and reduce the risk of it being overlooked.', 
 'Use a consistent format for documenting requirements to enhance clarity and understanding among all stakeholders.', 
 'Avoid documenting requirements that involve complex logic, as these can be difficult for stakeholders to understand.', 
 'The software requirements specification (SRS) should be used to formally record the agreed-upon requirements and ensure all stakeholders have a shared understanding.', 
 '', 
 '', 
 'BD'),
('Which of the following statements accurately describes the role of a business analyst in a project? Select two.', 
 'The business analyst is solely responsible for managing communication between the customers and the development team.', 
 'The business analyst primarily focuses on eliciting, analyzing, documenting, and validating the needs of the project stakeholders.', 
 'In agile projects, the business analyst often acts as the project manager, handling both internal and external project tasks', 
 'The business analyst plays a central role in collecting and disseminating product information, while the project manager focuses on communicating project information.', 
 '', 
 '', 
 'BD'),
('Which of the following are considered good practices in requirements elicitation? Select two.', 
 'Defining the product vision and project scope early in the project to ensure all stakeholders have a shared understanding.', 
 'Focusing exclusively on nonfunctional requirements during initial elicitation while ignoring functional requirements to save time.', 
 'Identifying user classes and their characteristics to ensure that all user needs are considered.', 
 'Avoiding the use of prototypes in the early stages of requirements elicitation to prevent biasing stakeholders.', 
 '', 
 '', 
 'AC'),
('Which of the following are advantages of reusing requirements? (Choose 2 answers)', 
 'Decreased consistency', 
 'Reduced rework', 
 'Lower development costs', 
 'Increased number of defects', 
 '', 
 '', 
 'BC'),
('Which of the following statements accurately describes the purpose and use of personas in requirements analysis? Select two.', 
 'A persona is a real user from the target audience, used to validate requirements and ensure they meet actual user needs.', 
 'Personas are hypothetical, generic users representing a group with similar characteristics, used to understand requirements and design user experiences.', 
 'Creating a persona helps bring user classes to life and aids in visualizing how different types of users will interact with the system', 
 'Personas are only useful during the testing phase to ensure that the application functions as expected for diverse user groups.', 
 '', 
 '', 
 'BC'),
('Which of the following statements correctly distinguishes between product requirements and project requirements? Select two.', 
 'Product requirements describe the physical resources and training needs necessary for project completion.', 
 'Project requirements include staff training and infrastructure changes needed in the operating environment.', 
 'Project requirements are housed in the SRS along with product requirements.', 
 'Product requirements focus on the characteristics and functionalities of the software system being built.', 
 '', 
 '', 
 'BD'),
 ('Which of the following statements about the requirements development process'' framework is accurate? Select two.', 
 'The process of requirements development is strictly linear, moving from elicitation to validation without any need for revisiting previous stages.', 
 'Elicitation, analysis, specification, and validation are iterative activities that may require revisiting earlier stages to ensure accuracy and completeness.', 
 'Validation is only performed at the end of the project to confirm that all requirements have been met.', 
 'The framework allows for flexibility, with steps often revisited throughout the project to refine and correct requirements as needed.', 
 '', 
 '', 
 'BD'),
('Which of the following statements accurately describe the use of context diagrams in representing project scope? Select two.', 
 'A context diagram visually illustrates the boundary between the system being developed and external entities that interact with it.', 
 'The context diagram includes detailed information about the system''s internal processes and data.', 
 'The primary purpose of a context diagram is to depict the interactions between the system and external entities without detailing the internal workings of the system.', 
 'Context diagrams are typically used to represent the relationship between user interfaces and system components within the boundary.', 
 '', 
 '', 
 'AC'),
('Which of the following statements accurately describes the purpose and use of personas in requirements analysis? Select two.', 
 'A persona is a real user from the target audience, used to validate requirements and ensure they meet actual user needs.', 
 'Personas are hypothetical, generic users representing a group with similar characteristics, used to understand requirements and design user experiences.', 
 'Creating a persona helps bring user classes to life and aids in visualizing how different types of users will interact with the system.', 
 'Personas are only useful during the testing phase to ensure that the application functions as expected for diverse user groups.', 
 '', 
 '', 
 'BC'),
('Which of the following statements accurately describe preconditions and postconditions in the context of use cases? Select two.', 
 'Preconditions define the prerequisites that must be met before the system can begin executing a use case.', 
 'Preconditions describe the expected outcome after the use case has been successfully executed.', 
 'Postconditions describe the state of the system after the use case has executed successfully.', 
 'Postconditions determine whether the system should proceed with executing a use case.', 
 '', 
 '', 
 'AC'),
('Which of the following statements accurately describes a business rule? Select two.', 
 'A business rule is a statement that defines or constrains some aspect of the business to control or influence its behavior.', 
 'Business rules are only relevant for heavily rules-driven systems and can be ignored in simpler systems.', 
 'Classifying business rules helps in understanding how they might be applied in a software application, such as using constraints to enforce certain conditions.', 
 'A business rule is the same as a system requirement, focusing solely on the technical implementation details.', 
 '', 
 '', 
 'AC'),
('Which of the following statements accurately describe the use case approach? Select two.', 
 'A use case describes a sequence of interactions between a system and an external actor that results in an outcome of value to the actor.', 
 'In a use case diagram, the boundary between what''s inside and outside the system is not explicitly defined.', 
 'Actors in a use case can include both human users and other systems that interact with the system being developed.', 
 'The primary actor in a use case is always the system itself, as it initiates and controls all interactions.', 
 '', 
 '', 
 'AC'),
('Which of the following characteristics should a well-written requirement statement exhibit? Select two.', 
 'Each requirement should be complete, meaning it contains all the information necessary for the reader to understand it and for developers to implement it correctly.', 
 'A requirement statement can be ambiguous as long as it is feasible to implement.', 
 'Requirements should be prioritized based on their importance to achieving the desired business value, and should be assigned an implementation priority.', 
 'Verifiabilty of a requirement is optional as long as it meets stakeholder needs.', 
 '', 
 '', 
 'AC'),
('Which type of requirement best describes the behavior and information that the solution will manage, including specific system actions or responses?', 
 'Stakeholder Requirements.', 
 'Functional Requirements.', 
 'Business Requirements.', 
 'Non-functional Requirements.', 
 '', 
 '', 
 'B'),
('When defining the scope and limitations of a product, which of the following practices should be followed? Select two.', 
 'List the product''s major features or user capabilities, focusing on those that distinguish it from competitors.', 
 'Include all possible features in the scope to ensure nothing is left out, even if some may be unnecessary.', 
 'Clearly define the features that will be included in the initial release and those that will be excluded.', 
 'Avoid mentioning any limitations or exclusions to keep the focus on what the product will do.', 
 '', 
 '', 
 'AC'),
('When specifying the level of detail in software requirements, which of the following practices should be considered? Select two.', 
 'It is always necessary to specify all requirements at the same high level of detail to ensure consistency.', 
 'More detail should be included when the work is being done for an external client or when system testing will be based on the requirements.', 
 'Less detail can be included if the work is being done internally for your company and developers have considerable domain experience.', 
 'Writing all requirements at a very fine-grained level is always better, regardless of the project''s context.', 
 '', 
 '', 
 'BC'),
 ('When choosing the appropriate representation techniques for analysis models, which of the following guidelines should be followed? Select two.', 
 'Business process flows can be represented with high-level data flow diagrams or Swimlane diagrams that show roles and responsibilities in the process.', 
 'Use only one type of model to avoid confusion and ensure clarity throughout the development process.', 
 'Complex logic can be effectively represented using decision trees or decision tables, which show possible outcomes or unique functional requirements.', 
 'Data relationships should be illustrated using state-transition diagrams or storyboard models.', 
 '', 
 '', 
 'AC'),
('How can a business analyst effectively translate the voice of the customer into specific model components? Select two.', 
 'By focusing exclusively on the nouns mentioned by customers, as they represent the most critical elements.', 
 'By identifying keywords such as nouns, verbs, and conditional statements that can be mapped to corresponding analysis model components.', 
 'By using a predetermined set of model components without considering the specific word choices of the customer.', 
 'By mapping verbs mentioned by customers to processes, activities, and use cases in the analysis models.', 
 '', 
 '', 
 'BD'),
('Why is clear communication crucial in acquirer-supplier interactions in outsourced projects? (Choose 2 answers)', 
 'It reduces the need for collaboration.', 
 'It ensures both parties understand each other''s needs and capabilities.', 
 'It helps in resolving potential issues early.', 
 'It allows unilateral decision-making by the supplier', 
 '', 
 '', 
 'BC'),
('In the context of requirements tracing, what is a traceability matrix used for? (Choose 2 answers)', 
 'To track project progress in real-time', 
 'To generate new requirements automatically', 
 'To map requirements to other system elements like design and code', 
 'To identify missing or unnecessary requirements', 
 '', 
 '', 
 'CD'),
('Two important goals of writing requirements are that:', 
 'Anyone who reads the requirement comes to the same interpretation as any other reader.', 
 'Each reader''s interpretation matches what the author intended to communicate.', 
 'Developers find the requirements technically easy to understand.', 
 'Customers are happy.', 
 '', 
 '', 
 'AB'),
('We can reuse all authentication requirements from the previous project by copy from a library of reusable components. Which dimensions does the statement refer to?', 
 'extent of modification', 
 'reuse mechanism', 
 'extent of reuses', 
 '', 
 '', 
 '', 
 'BC');


--- 3 ANSWER
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, option_e, option_f, correct_answer) VALUES
('What is true about a software prototype? Choose 3 correct answers.', 
 'It is a partial implementation of a proposed new product.', 
 'It is a possible implementation of a proposed new product.', 
 'It is a preliminary implementation of a proposed new product.', 
 'It is a complete implementation of a proposed new product.', 
 '', 
 '', 
 'ABC'),
('What are the tasks of a business analyst? Choose 3 correct answers.', 
 'Define business requirements', 
 'Identify project stakeholders and user classes', 
 'Document requirements', 
 'Lead requirements prioritization', 
 '', 
 '', 
 'ABC'),
('What potential issues can be prevented by validating requirements? (Select all that apply)', 
 'Scope creep', 
 'Eliminating All Bugs', 
 'Misaligned Expectations', 
 'Cost Overruns and Delays', 
 '', 
 '', 
 'ACD'),
('What should a business analyst do in an Agile project? Chooses 3 correct answers.', 
 'Define a lightweight, flexible requirements process and adapt it as the project warrants', 
 'Ensure that requirements documentation is at the right level: very detailed', 
 'Help validate that customer needs are accurately represented in the product backlog', 
 'Facilitate backlog prioritization', 
 '', 
 '', 
 'ACD'),
('Which of the following are considered good practices in requirements analysis? Select three.', 
 'Modeling the application environment to understand the system''s boundaries and interactions with external entities.', 
 'Prioritizing the requirements based solely on the preferences of the development team without considering business goals or customer needs.', 
 'Creating prototypes to explore and validate uncertain requirements with stakeholders.', 
 'Analyzing data flows to ensure that all interactions between the system and external entities are understood and documented.', 
 '', 
 '', 
 'ACD'),
('Which of the following are common places and ways to look for business rules? Choose 3 correct answers.', 
 '"Common knowledge" from the organization, often collected from individuals who have worked with the business for a long time and know the details of how it operates.', 
 'Legacy systems that embed business rules in their requirements and code.', 
 'Analysis of existing documentation, including requirements specifications from earlier projects, regulations, industry standards, corporate policy documents, contracts, and business plans.', 
 'Business laws', 
 '', 
 '', 
 'ABC'),
('Which of the following are true about a dashboard? Choose 3 correct answers.', 
 'It is a screen display or printed report.', 
 'It uses multiple textual and/or graphical representations of data.', 
 'It aims to provide a consolidated, multidimensional view of what is going on in an organization or a process.', 
 'It is a brochure to promote the product', 
 '', 
 '', 
 'ABC'),
('Which of the following factors should be considered when classifying users? Select three.', 
 'The platform they will be using, such as desktop PCs, laptops, tablets, or smartphones.', 
 'The specific languages used in the system''s backend processes.', 
 'The frequency with which they use the product and the tasks they perform during business operations.', 
 'Their access privileges or security levels, such as ordinary user, guest user, or administrator.', 
 '', 
 '', 
 'ACD'),
('Which of the following skills are essential for a business analyst? Select three.', 
 'Literacy skills for effectively interpreting written material and communicating requirements.', 
 'Technical skills to ensure the analyst can implement the software they are analyzing.', 
 'Facilitation skills to manage group discussions and ensure effective participation from all stakeholders.', 
 'Analytical skills to break down complex problems and identify feasible solutions.', 
 '', 
 '', 
 'ACD'),
('Which of the following elements should be included when crafting a vision statement? Select three.', 
 'The specific target customer for whom the product is intended.', 
 'A detailed technical specification of the product''s architecture.', 
 'The key benefit or compelling reason for the customer to buy or use the product.', 
 'A comparison with the primary competitive alternative or current system.', 
 '', 
 '', 
 'ACD'),
('Which of the following are the signals indicating that you have completed requirements elicitation? Choose 3 correct answers.', 
 'Users repeat issues they already covered in previous discussions.', 
 'Suggested new features, user requirements, or functional requirements are all deemed to be out of scope.', 
 'Proposed new requirements are all low priority.', 
 'Developers and testers who review the requirements for an area raise many questions.', 
 '', 
 '', 
 'ABC'),
('Why do we have to label the requirements in a software requirements specification (SRS)? (Choose 3 correct answers)', 
 'It allows us to refer to specific requirements in a change request, modification history, cross-reference, or requirements traceability matrix.', 
 'It enables reusing the requirements in multiple projects.', 
 'It facilitates collaboration between team members when they''re discussing requirements.', 
 'It makes the SRS look more professional.', 
 '', 
 '', 
 'ABC'),
 ('When documenting data requirements for a system, which of the following practices should be followed? Select three.', 
 'Include a detailed implementation data model directly in the SRS to ensure clarity in the system''s design.', 
 'Create a data dictionary that defines the composition, meaning, data type, and allowed values for all data elements the system will handle.', 
 'Document any reports that the application will generate, focusing on their logical descriptions and deferring detailed layouts to the design stage.', 
 'Describe how data will be acquired, maintained, and protected, including policies for data retention, disposal, and ensuring data integrity.', 
 '', 
 '', 
 'BCD'),
('Customers have the right to: (choose 3 correct answers)', 
 'expect business analysts to learn about their business and their objectives', 
 'describe characteristics that will make the product easy to use', 
 'receive a system that meets their functional needs and quality expectations', 
 'promptly communicate changes to the requirements', 
 '', 
 '', 
 'ABC'),
('Entries in the data dictionary represent the following types of data elements: (choose 3 correct answers)', 
 'Primitive', 
 'Structure', 
 'Repeating group', 
 'Virtual', 
 '', 
 '', 
 'ABC'),
('In software development, what do requirements drive? Choose 3 correct answers.', 
 'Project planning', 
 'Design and coding', 
 'Testing activities', 
 'Financial activities', 
 '', 
 '', 
 'ABC'),
('The benefits of effective requirements reuse include: (choose 3 correct answers)', 
 'faster delivery', 
 'lower development costs', 
 'reduced rework', 
 'fewer test cases', 
 '', 
 '', 
 'ABC'),
('Requirement statements must be: (Choose 3 correct answers)', 
 'Feasible', 
 'Correct', 
 'Verifiable', 
 'Flexible', 
 '', 
 '', 
 'ABC');



 --- SIGNAL _______
INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, option_e, option_f, correct_answer) VALUES
('While a mock-up is called a_____prototype, a proof of concept is called a_____prototype.', 
 'horizontal, vertical', 
 'vertical, horizontal', 
 'primary, secondary', 
 'front-end, back-end', 
 '', 
 '', 
 'A'),
('Prioritization is a way to deal with competing demands for limited resources. So, establishing the relative priority of each product capability lets you plan construction to provide the_____value at the_____cost.', 
 'highest, lowest', 
 'lowest, highest', 
 'highest, highest', 
 'lowest, lowest', 
 '', 
 '', 
 'A'),
('Customers are a(n)_____of stakeholders.', 
 'subset', 
 'representative', 
 'partner', 
 'equivalent', 
 '', 
 '', 
 'A'),
('Consider the following statement: "All the screens in the system must load quickly". This requirement statement is_____', 
 'Correct and Feasible', 
 'Unambiguous and Testable', 
 'Unambiguous and Non-Testable', 
 'Ambiguous and Non-Testable', 
 '', 
 '', 
 'D'),
('Fill in the blank. 
"Define vision and scope", "select product champions" activities should be done_____stage', 
 'Specifications', 
 'Validation', 
 'Elicitation', 
 'Analysis stage.', 
 '', 
 '', 
 'C'),
('Fill in the blank.
_____is a visual representation of the data objects and collections the system will process, and the relationships between them', 
 'Use case diagram', 
 'Data model', 
 'Data dictionary', 
 'Reports', 
 '', 
 '', 
 'B'),
('In the specification of a use case, conditions that have the potential to prevent a use case from succeeding are called______', 
 'exceptions', 
 'alternative flows', 
 'secondary scenarios', 
 'backup flows', 
 '', 
 '', 
 'A'),
('Product backlogs typically are_____', 
 'user stories', 
 'defects', 
 'user stories and defects', 
 'prototype', 
 '', 
 '', 
 'C'),
('Validation of requirements assesses whether you have written_____', 
 'the right requirements', 
 'the requirements right', 
 'the flexible requirements', 
 'the variable requirements', 
 '', 
 '', 
 'A');


--- NOT OR IS TRUE
 INSERT INTO QuizQuestions (question, option_a, option_b, option_c, option_d, option_e, option_f, correct_answer) VALUES
('What is not the purpose of a Use Case Diagram?',
 'Use case diagrams are both behavior diagrams because they describe the behavior of the system. They are also structure diagrams, serving as a special case of class diagrams where classifiers are restricted to be either actors or use cases related to each other with associations.',
 'Use case diagrams show the graphical user interface that needs to be implemented.',
 'Use case diagrams are usually referred to as behavior diagrams used to describe a set of actions (use cases) that some system or systems (subject) should or can perform in collaboration with one or more external users of the system (actors).',
 'A use case describes a sequence of interactions between a system and an external actor that results in the actor being able to achieve some outcome of value.',
 '',
 '',
 'B'),
('Which of the following is NOT an intended audience for a Software Requirements Specification (SRS)?',
 'Project Managers',
 'Testers',
 'Legal Staff',
 'Hardware Manufacturers',
 'Documentation Writers',
 '',
 'D'),
('Which of the following is NOT considered a dimension of requirements reuse when adapting requirements from one project to another?',
 'The extent of reuse, including whether individual requirement statements or sets of requirements with their associated elements are reused.',
 'Reuse frequency, which measures how often a particular requirement has been reused in different projects.',
 'The extent of modification, which considers the degree to which reused requirements must be altered to fit the new project''s context.',
 'The reuse mechanism, which involves how the requirement is reused, such as copying from a library of reusable requirements or referring to the original source.',
 '',
 '',
 'B'),
('Which of the following is NOT a type of business rule according to the taxonomy?',
 'Fact Rules',
 'Action Enabler Rules',
 'Constraint Rules',
 'Operational Rules',
 '',
 '',
 'D'),
('Which of the following is NOT a characteristic of Software as a Service (SaaS)?',
 'Subscription-based pricing',
 'On-premises deployment',
 'Centralized hosting',
 'Internet accessibility',
 '',
 '',
 'B'),
('Which of the following is NOT a requirements prioritization technique?',
 'Pairwise comparison',
 'In or out',
 'Three-level scale',
 '$1000',
 'MoSCoW',
 '',
 'D'),
('Which of the following does NOT suggest an overall description of the Software Requirements Specification template?',
 'Product perspective',
 'User classes and characteristics',
 'Operating environment',
 'Design and implementation constraints',
 'Assumptions and dependencies',
 'System feature',
 'F'),
('Which of the following is NOT included in the list of Software Bill of Rights Requirements?',
 'Expect BAs to speak your language.',
 'Expect BAs to learn about your business and your objectives.',
 'Promptly communicate changes to the requirements.',
 'Receive explanations of requirements practices and deliverables.',
 'Change your requirements.',
 'Expect an environment of mutual respect.',
 'C'),
('Which of the following is NOT about Agile project?',
 'Developers have little interaction with customers after construction begins on projects.',
 'It encourages creating the minimum amount of documentation needed to accurately guide the developers and testers.',
 'BAs or other people responsible for requirements will develop the necessary precision through conversations and documentation when it is needed.',
 'The collaboration of customers with developers on agile projects generally means that requirements can be documented in less detail.',
 '',
 '',
 'A'),
('Which of the following is NOT about outsourced projects?',
 'It takes advantage of development skills they have available in-house.',
 'It''s harder to get developer input on requirements and to pass along user feedback on delivered software to developers.',
 'A formal contractual definition of requirements is necessary, which can lead to contention if differences of interpretation are discovered late in the project.',
 '',
 '',
 '',
 'A'),
('Which of the following is NOT about packaged solution?',
 'You build systems by using your own staff.',
 'It needs to be configured, integrated, and extended to work in the target environment.',
 'You can purchase a package as part or all of the solution for a new project.',
 'Evaluate solution candidates so that you can select the most appropriate package.',
 '',
 '',
 'A'),
('Which of the following is NOT a purpose of creating a mock-up?',
 'To refine user interface design.',
 'To test architectural feasibility.',
 'To allow users to judge the overall workflow and requirements.',
 'To simulate a user interface with no real functionality.',
 '',
 '',
 'B'),
('Which one of these is NOT a Business analyst''s task?',
 'Communicate requirements',
 'Document requirements',
 'Analyze requirements',
 'Assure requirements',
 'Elicit requirements',
 '',
 'D'),
('Which of the following is NOT about prioritization techniques?',
 'In or out.',
 'Pairwise comparison and rank ordering.',
 'Three-level scale.',
 'MoSCoW.',
 'Based on risk',
 '',
 'E'),
('Which of the following is NOT about Change management on Agile projects?',
 'Agile processes harness change for the customer''s competitive advantage.',
 'Agile projects manage change by maintaining a specific backlog of work to be done.',
 'Accepting change helps to meet evolving business objectives and priorities and to accommodate the limitations of human plans and foresight.',
 'Agile methods vary as to their philosophy on this point; there is no single "correct" approach.',
 '',
 '',
 'D'),
('Which is NOT an activity of risk management?',
 'Risk avoidance',
 'Risk assessment',
 'Risk monitoring',
 'Risk control',
 '',
 '',
 'A'),
('Which of the following is NOT characteristic of the user?',
 'A subset of the product''s customers in some cases',
 'A subset of the product''s users',
 'A superset of stakeholders',
 'Includes direct users and indirect users',
 '',
 '',
 'C'),
('Which of the following statements is TRUE about Use Cases?',
 'Use Cases are static and do not evolve throughout the software development process.',
 'Use case diagrams are the primary tool to document requirements.',
 'Use Cases are not useful in capturing user requirements.',
 'Use Cases describe the interactions between the system and external entities.',
 '',
 '',
 'D');
